# Generated by Django 5.0.6 on 2026-03-22 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('flood_warning', 'Flood Warning'), ('heavy_rain', 'Heavy Rain'), ('dam_release', 'Dam Release'), ('acquisition', 'Government Acquisition'), ('system', 'System Notification')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
