# Generated by Django 5.0.6 on 2026-03-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='land_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='scans.landscan'),
        ),
    ]
