# Generated by Django 5.1.15 on 2026-04-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='authorization_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
