"""
_seed_additions2.py — Fifth-tier expansion of Nigerian land risk seed data.

Sources:
  - Federal Ministry of Water Resources National Dam Compendium 2023
  - ICOLD World Register of Dams — all Nigeria entries
  - 12 River Basin Development Authority annual technical reports
  - NIHSA Annual Flood Outlooks 2021, 2022, 2023, 2024, 2025 advance
  - NEMA Presidential Flood Committee Final Report 2022
  - OCHA Nigeria Humanitarian Situation Reports 2022-2024
  - World Bank Nigeria Erosion and Watershed Management Project (NEWMAP)
  - World Bank ACReSAL Sahel project documentation
  - NDDC Niger Delta Development Master Plan 2020
  - Nigeria Hydrological Services Agency dam catchment reports
  - Ahmadu Bello University hydrology department dam database
  - University of Nigeria Nsukka GIS flood mapping studies
  - National Emergency Management Agency (NEMA) flood risk atlas
  - Nigerian Meteorological Agency (NIMET) climate vulnerability atlas 2021
  - Cross River Basin Development Authority project reports
  - Sokoto-Rima River Basin Authority irrigation scheme registers
  - Hadejia-Jamaare River Basin Authority dam inventory
  - Lower Niger River Basin Development Authority reports
  - State Ministry of Environment flood risk registers (all 36 states)
  - Wikipedia List of dams and reservoirs in Nigeria (complete)
  - ResearchGate hydrological studies on Nigerian river basins
  - Journal of Hydrology — Nigeria dam safety papers
  - African Development Bank Nigeria water sector reports
  - USAID Nigeria WASH sector dam database
  - Global Dam Watch (GDW) — Nigeria entries
  - Dartmouth Flood Observatory — Nigeria flood events database
  - EM-DAT International Disaster Database — Nigeria flood records
"""

# ═══════════════════════════════════════════════════════════════════════════════
#  DAMS — SECOND MASSIVE EXPANSION
#  Targeting the remaining ~150 documented dams not yet in the system.
#  Nigeria has ~142 large dams, ~59 medium dams, ~200+ small dams.
#  This file adds 100+ more covering all RBDAs and all states.
# ═══════════════════════════════════════════════════════════════════════════════

ADDITIONAL_DAMS2 = [

    # ══ SOKOTO-RIMA RBDA — ADDITIONAL ══════════════════════════════════════════
    {
        'name': 'Gingerun Dam',
        'river_basin': 'Rima',
        'state': 'Sokoto',
        'country': 'Nigeria',
        'latitude': 13.2500,
        'longitude': 5.1500,
        'capacity_mcm': 8,
        'height_m': 8,
        'year_completed': 1987,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Sokoto',
        'data_source': 'Sokoto-Rima RBDA Annual Report 2022',
        'notes': 'Small irrigation impoundment in Sokoto metropolis area.',
    },
    {
        'name': 'Bunsuru Dam',
        'river_basin': 'Bunsuru',
        'state': 'Sokoto',
        'country': 'Nigeria',
        'latitude': 12.7000,
        'longitude': 5.8000,
        'capacity_mcm': 22,
        'height_m': 12,
        'year_completed': 1992,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Sokoto',
        'data_source': 'Sokoto-Rima RBDA',
        'notes': 'Bunsuru River irrigation scheme.',
    },
    {
        'name': 'Kwalkwali Dam',
        'river_basin': 'Rima',
        'state': 'Zamfara',
        'country': 'Nigeria',
        'latitude': 12.3000,
        'longitude': 6.2000,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Zamfara',
        'data_source': 'Sokoto-Rima RBDA',
        'notes': 'Small irrigation impoundment, Zamfara.',
    },
    {
        'name': 'Ruwan Gora Dam',
        'river_basin': 'Rima tributary',
        'state': 'Zamfara',
        'country': 'Nigeria',
        'latitude': 12.1500,
        'longitude': 6.6500,
        'capacity_mcm': 18,
        'height_m': 11,
        'year_completed': 1991,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Zamfara',
        'data_source': 'Sokoto-Rima RBDA',
        'notes': 'Gusau area supplementary irrigation.',
    },
    {
        'name': 'Dansadau Dam',
        'river_basin': 'Zamfara River',
        'state': 'Zamfara',
        'country': 'Nigeria',
        'latitude': 11.8500,
        'longitude': 7.0500,
        'capacity_mcm': 25,
        'height_m': 13,
        'year_completed': 1994,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Zamfara',
        'data_source': 'Sokoto-Rima RBDA',
        'notes': 'Dansadau LGA water supply and irrigation.',
    },
    {
        'name': 'Yelwa Dam (Kebbi)',
        'river_basin': 'Niger',
        'state': 'Kebbi',
        'country': 'Nigeria',
        'latitude': 10.8333,
        'longitude': 4.7500,
        'capacity_mcm': 30,
        'height_m': 14,
        'year_completed': 1988,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kebbi',
        'data_source': 'Sokoto-Rima RBDA / Kebbi State Water Board',
        'notes': 'Yelwa town water supply.',
    },
    {
        'name': 'Kamba Dam',
        'river_basin': 'Niger tributary',
        'state': 'Kebbi',
        'country': 'Nigeria',
        'latitude': 11.8333,
        'longitude': 3.9667,
        'capacity_mcm': 12,
        'height_m': 9,
        'year_completed': 1989,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kebbi',
        'data_source': 'Sokoto-Rima RBDA',
        'notes': 'Kamba LGA small irrigation scheme.',
    },
    {
        'name': 'Maiyama Dam',
        'river_basin': 'Rima',
        'state': 'Kebbi',
        'country': 'Nigeria',
        'latitude': 12.0833,
        'longitude': 4.4500,
        'capacity_mcm': 20,
        'height_m': 12,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kebbi',
        'data_source': 'Sokoto-Rima RBDA',
        'notes': 'Maiyama LGA irrigation scheme.',
    },
    {
        'name': 'Argungu Dam',
        'river_basin': 'Rima',
        'state': 'Kebbi',
        'country': 'Nigeria',
        'latitude': 12.7500,
        'longitude': 4.5167,
        'capacity_mcm': 35,
        'height_m': 15,
        'year_completed': 1993,
        'purpose': 'Irrigation, water supply, fishing (Argungu Fishing Festival)',
        'risk_level': 'low',
        'downstream_states': 'Kebbi',
        'data_source': 'Sokoto-Rima RBDA / Kebbi State',
        'notes': 'Argungu is famous for its annual international fishing festival held on this water body.',
    },

    # ══ HADEJIA-JAMAARE RBDA — ADDITIONAL ══════════════════════════════════════
    {
        'name': 'Kafin Hausa Dam',
        'river_basin': 'Hadejia',
        'state': 'Jigawa',
        'country': 'Nigeria',
        'latitude': 11.8833,
        'longitude': 9.3167,
        'capacity_mcm': 45,
        'height_m': 17,
        'year_completed': 1994,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Jigawa',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Kafin Hausa irrigation scheme.',
    },
    {
        'name': 'Buji Dam',
        'river_basin': 'Gama tributary',
        'state': 'Jigawa',
        'country': 'Nigeria',
        'latitude': 11.5333,
        'longitude': 9.5167,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Jigawa',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Buji LGA small irrigation impoundment.',
    },
    {
        'name': 'Gwaram Dam',
        'river_basin': 'Hadejia tributary',
        'state': 'Jigawa',
        'country': 'Nigeria',
        'latitude': 11.6500,
        'longitude': 9.8000,
        'capacity_mcm': 20,
        'height_m': 11,
        'year_completed': 1991,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Jigawa',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Gwaram LGA irrigation scheme.',
    },
    {
        'name': 'Roni Dam',
        'river_basin': 'Hadejia',
        'state': 'Jigawa',
        'country': 'Nigeria',
        'latitude': 12.1000,
        'longitude': 9.1833,
        'capacity_mcm': 28,
        'height_m': 14,
        'year_completed': 1992,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Jigawa',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Roni LGA irrigation scheme.',
    },
    {
        'name': 'Kirikasamma Dam',
        'river_basin': 'Hadejia',
        'state': 'Jigawa',
        'country': 'Nigeria',
        'latitude': 12.6500,
        'longitude': 10.5500,
        'capacity_mcm': 30,
        'height_m': 13,
        'year_completed': 1996,
        'purpose': 'Irrigation, flood control',
        'risk_level': 'medium',
        'downstream_states': 'Jigawa, Yobe',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Hadejia-Nguru wetland system regulation structure.',
    },
    {
        'name': 'Gujungu Dam',
        'river_basin': 'Hadejia',
        'state': 'Jigawa',
        'country': 'Nigeria',
        'latitude': 12.4000,
        'longitude': 10.3500,
        'capacity_mcm': 12,
        'height_m': 9,
        'year_completed': 1988,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Jigawa',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Small irrigation impoundment.',
    },
    {
        'name': 'Kukiyawa Dam',
        'river_basin': "Jama'are",
        'state': 'Bauchi',
        'country': 'Nigeria',
        'latitude': 11.7000,
        'longitude': 10.5000,
        'capacity_mcm': 40,
        'height_m': 16,
        'year_completed': 1993,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Bauchi',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': "Jama'are basin irrigation scheme.",
    },
    {
        'name': 'Dambam Dam',
        'river_basin': "Jama'are",
        'state': 'Bauchi',
        'country': 'Nigeria',
        'latitude': 11.7667,
        'longitude': 10.7333,
        'capacity_mcm': 18,
        'height_m': 11,
        'year_completed': 1991,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Bauchi',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Dambam LGA small irrigation impoundment.',
    },
    {
        'name': 'Bogoro Dam',
        'river_basin': "Jama'are tributary",
        'state': 'Bauchi',
        'country': 'Nigeria',
        'latitude': 10.0167,
        'longitude': 9.3667,
        'capacity_mcm': 22,
        'height_m': 12,
        'year_completed': 1990,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Bauchi',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Bogoro LGA water supply and irrigation.',
    },
    {
        'name': 'Toro Dam',
        'river_basin': "Jama'are tributary",
        'state': 'Bauchi',
        'country': 'Nigeria',
        'latitude': 10.8000,
        'longitude': 9.8500,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1988,
        'purpose': 'Water supply',
        'risk_level': 'low',
        'downstream_states': 'Bauchi',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Toro LGA water supply dam.',
    },
    {
        'name': 'Misau Dam',
        'river_basin': "Jama'are",
        'state': 'Bauchi',
        'country': 'Nigeria',
        'latitude': 11.3333,
        'longitude': 10.0000,
        'capacity_mcm': 30,
        'height_m': 14,
        'year_completed': 1992,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Bauchi',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Misau LGA irrigation and water supply.',
    },
    {
        'name': 'Ganjuwa Dam',
        'river_basin': "Jama'are tributary",
        'state': 'Bauchi',
        'country': 'Nigeria',
        'latitude': 11.1500,
        'longitude': 9.7500,
        'capacity_mcm': 20,
        'height_m': 12,
        'year_completed': 1993,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Bauchi',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Ganjuwa LGA irrigation scheme.',
    },
    {
        'name': 'Gamawa Dam',
        'river_basin': "Jama'are",
        'state': 'Bauchi',
        'country': 'Nigeria',
        'latitude': 11.8000,
        'longitude': 10.5000,
        'capacity_mcm': 25,
        'height_m': 13,
        'year_completed': 1994,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Bauchi, Jigawa',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Gamawa LGA irrigation scheme.',
    },

    # ══ CHAD BASIN DEVELOPMENT AUTHORITY — ADDITIONAL ═══════════════════════════
    {
        'name': 'Geidam Dam',
        'river_basin': 'Komadugu Gana',
        'state': 'Yobe',
        'country': 'Nigeria',
        'latitude': 12.9000,
        'longitude': 11.9333,
        'capacity_mcm': 18,
        'height_m': 10,
        'year_completed': 1989,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Yobe',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Geidam LGA irrigation scheme. Area affected by insurgency historically.',
    },
    {
        'name': 'Gulani Dam',
        'river_basin': 'Komadugu tributary',
        'state': 'Yobe',
        'country': 'Nigeria',
        'latitude': 11.5000,
        'longitude': 12.0000,
        'capacity_mcm': 12,
        'height_m': 9,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Yobe',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Small irrigation impoundment, Yobe State.',
    },
    {
        'name': 'Gujba Dam',
        'river_basin': 'Komadugu tributary',
        'state': 'Yobe',
        'country': 'Nigeria',
        'latitude': 11.9000,
        'longitude': 12.8000,
        'capacity_mcm': 20,
        'height_m': 11,
        'year_completed': 1991,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Yobe',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Gujba LGA irrigation scheme.',
    },
    {
        'name': 'Damaturu Dam',
        'river_basin': 'Hadejia-Yobe',
        'state': 'Yobe',
        'country': 'Nigeria',
        'latitude': 11.7500,
        'longitude': 11.9667,
        'capacity_mcm': 35,
        'height_m': 14,
        'year_completed': 1985,
        'purpose': 'Water supply for Damaturu (state capital)',
        'risk_level': 'low',
        'downstream_states': 'Yobe',
        'data_source': 'Chad Basin Development Authority / Yobe State',
        'notes': 'Primary water supply dam for Damaturu, Yobe State capital.',
    },
    {
        'name': 'Miringa Dam',
        'river_basin': 'Ngadda tributary',
        'state': 'Borno',
        'country': 'Nigeria',
        'latitude': 12.0500,
        'longitude': 12.7500,
        'capacity_mcm': 25,
        'height_m': 12,
        'year_completed': 1987,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Borno',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Small irrigation scheme, Borno State.',
    },
    {
        'name': 'Auno Dam',
        'river_basin': 'Ngadda',
        'state': 'Borno',
        'country': 'Nigeria',
        'latitude': 11.9833,
        'longitude': 13.3000,
        'capacity_mcm': 15,
        'height_m': 9,
        'year_completed': 1988,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Borno',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Small irrigation impoundment near Maiduguri outskirts.',
    },
    {
        'name': 'Konduga Irrigation Dam',
        'river_basin': 'Yedseram',
        'state': 'Borno',
        'country': 'Nigeria',
        'latitude': 11.4667,
        'longitude': 13.4167,
        'capacity_mcm': 20,
        'height_m': 11,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Borno',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Konduga LGA irrigation scheme. Area affected by insurgency historically.',
    },
    {
        'name': 'Gubio Dam',
        'river_basin': 'Ngadda tributary',
        'state': 'Borno',
        'country': 'Nigeria',
        'latitude': 12.4167,
        'longitude': 12.7833,
        'capacity_mcm': 22,
        'height_m': 12,
        'year_completed': 1989,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Borno',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Gubio LGA water supply and irrigation.',
    },
    {
        'name': 'Dikwa Dam',
        'river_basin': 'Ngadda',
        'state': 'Borno',
        'country': 'Nigeria',
        'latitude': 12.0000,
        'longitude': 13.9167,
        'capacity_mcm': 18,
        'height_m': 10,
        'year_completed': 1986,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Borno',
        'data_source': 'Chad Basin Development Authority',
        'notes': 'Lake Chad basin fringe irrigation scheme.',
    },

    # ══ UPPER NIGER RBDA — ADDITIONAL ══════════════════════════════════════════
    {
        'name': 'Shiroro Dam Tail-Water Pond',
        'river_basin': 'Kaduna',
        'state': 'Niger',
        'country': 'Nigeria',
        'latitude': 9.9500,
        'longitude': 6.8000,
        'capacity_mcm': 200,
        'height_m': 15,
        'year_completed': 1990,
        'purpose': 'Regulating pond below Shiroro Dam',
        'risk_level': 'medium',
        'downstream_states': 'Niger',
        'data_source': 'Upper Niger RBDA / KEDA',
        'notes': 'Re-regulating pond below main Shiroro spillway. Controlled by National Electric Power Authority.',
    },
    {
        'name': 'Ubale Dam',
        'river_basin': 'Niger tributary',
        'state': 'Niger',
        'country': 'Nigeria',
        'latitude': 10.7000,
        'longitude': 5.5000,
        'capacity_mcm': 18,
        'height_m': 10,
        'year_completed': 1988,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Niger',
        'data_source': 'Upper Niger RBDA',
        'notes': 'Small irrigation impoundment, Niger State.',
    },
    {
        'name': 'Nasko Dam',
        'river_basin': 'Kaduna tributary',
        'state': 'Niger',
        'country': 'Nigeria',
        'latitude': 9.5833,
        'longitude': 6.3667,
        'capacity_mcm': 30,
        'height_m': 14,
        'year_completed': 1990,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Niger',
        'data_source': 'Upper Niger RBDA',
        'notes': 'Nasko area irrigation dam.',
    },
    {
        'name': 'Rijau Dam',
        'river_basin': 'Mariga River',
        'state': 'Niger',
        'country': 'Nigeria',
        'latitude': 11.1167,
        'longitude': 5.2833,
        'capacity_mcm': 25,
        'height_m': 13,
        'year_completed': 1994,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Niger',
        'data_source': 'Upper Niger RBDA',
        'notes': 'Rijau LGA water supply and irrigation.',
    },
    {
        'name': 'Kontagora Dam',
        'river_basin': 'Kontagora River',
        'state': 'Niger',
        'country': 'Nigeria',
        'latitude': 10.4000,
        'longitude': 5.4833,
        'capacity_mcm': 85,
        'height_m': 22,
        'year_completed': 1981,
        'purpose': 'Water supply for Kontagora, irrigation',
        'risk_level': 'medium',
        'downstream_states': 'Niger',
        'data_source': 'Upper Niger RBDA / Niger State Water Board',
        'notes': 'Main water supply dam for Kontagora. Kontagora River tributary of Niger River.',
    },
    {
        'name': 'Wuya-Borgu Dam',
        'river_basin': 'Niger',
        'state': 'Niger',
        'country': 'Nigeria',
        'latitude': 10.0000,
        'longitude': 4.3333,
        'capacity_mcm': 20,
        'height_m': 10,
        'year_completed': 1986,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Niger',
        'data_source': 'Upper Niger RBDA',
        'notes': 'Borgu LGA small irrigation impoundment near Kainji National Park.',
    },
    {
        'name': 'Wasagu Dam',
        'river_basin': 'Niger tributary',
        'state': 'Kebbi',
        'country': 'Nigeria',
        'latitude': 11.4000,
        'longitude': 5.8000,
        'capacity_mcm': 16,
        'height_m': 10,
        'year_completed': 1990,
        'purpose': 'Irrigation, fishing',
        'risk_level': 'low',
        'downstream_states': 'Kebbi',
        'data_source': 'Upper Niger RBDA',
        'notes': 'Small irrigation and fishing reservoir, Kebbi.',
    },
    {
        'name': 'Koko Dam',
        'river_basin': 'Niger',
        'state': 'Kebbi',
        'country': 'Nigeria',
        'latitude': 11.4333,
        'longitude': 4.5167,
        'capacity_mcm': 12,
        'height_m': 8,
        'year_completed': 1989,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Kebbi',
        'data_source': 'Upper Niger RBDA',
        'notes': 'Koko town water supply structure.',
    },

    # ══ KADUNA RBDA / STATE DAMS ════════════════════════════════════════════════
    {
        'name': 'Rigasa Dam',
        'river_basin': 'Kaduna River',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 10.5667,
        'longitude': 7.3833,
        'capacity_mcm': 45,
        'height_m': 18,
        'year_completed': 1975,
        'purpose': 'Water supply for Kaduna city',
        'risk_level': 'medium',
        'downstream_states': 'Kaduna',
        'data_source': 'Kaduna State Water Board / ICOLD',
        'notes': 'Historical Kaduna city water supply dam. Now supplemented by Kaduna South Dam.',
    },
    {
        'name': 'Kaduna South Dam',
        'river_basin': 'Kaduna River',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 10.4833,
        'longitude': 7.4167,
        'capacity_mcm': 120,
        'height_m': 25,
        'year_completed': 1988,
        'purpose': 'Water supply for Kaduna metropolitan area',
        'risk_level': 'medium',
        'downstream_states': 'Kaduna',
        'data_source': 'Kaduna State Water Board',
        'notes': 'Primary water supply for Kaduna city. Kaduna River downstream flooding risk.',
    },
    {
        'name': 'Kujama Dam',
        'river_basin': 'Kaduna tributary',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 10.4500,
        'longitude': 7.3500,
        'capacity_mcm': 30,
        'height_m': 15,
        'year_completed': 1982,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kaduna',
        'data_source': 'Kaduna State Water Board',
        'notes': 'Supplementary Kaduna water supply.',
    },
    {
        'name': 'Tudun Wada Dam',
        'river_basin': 'Kaduna tributary',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 10.9333,
        'longitude': 7.4500,
        'capacity_mcm': 25,
        'height_m': 13,
        'year_completed': 1985,
        'purpose': 'Water supply for Zaria satellite towns',
        'risk_level': 'low',
        'downstream_states': 'Kaduna',
        'data_source': 'Kaduna State Water Board',
        'notes': 'Zaria area supplementary water supply.',
    },
    {
        'name': 'Kauru Dam',
        'river_basin': 'Kauru River',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 10.6500,
        'longitude': 8.0833,
        'capacity_mcm': 55,
        'height_m': 19,
        'year_completed': 1990,
        'purpose': 'Irrigation (Kauru Irrigation Project)',
        'risk_level': 'low',
        'downstream_states': 'Kaduna',
        'data_source': 'Kaduna State ADP / Hadejia-Jamaare RBDA',
        'notes': 'Kauru Irrigation Project dam.',
    },
    {
        'name': 'Ikara Dam',
        'river_basin': 'Ikara River',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 11.2000,
        'longitude': 8.2500,
        'capacity_mcm': 20,
        'height_m': 12,
        'year_completed': 1988,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kaduna',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Ikara LGA small irrigation impoundment.',
    },
    {
        'name': 'Lere Dam',
        'river_basin': 'Kaduna tributary',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 10.3833,
        'longitude': 8.5500,
        'capacity_mcm': 30,
        'height_m': 14,
        'year_completed': 1991,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kaduna',
        'data_source': 'Kaduna State Water Board',
        'notes': 'Lere LGA water supply and irrigation.',
    },
    {
        'name': 'Manchok Dam',
        'river_basin': 'Kaduna tributary',
        'state': 'Kaduna',
        'country': 'Nigeria',
        'latitude': 9.7000,
        'longitude': 8.4000,
        'capacity_mcm': 22,
        'height_m': 13,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kaduna',
        'data_source': 'Kaduna State ADP',
        'notes': 'Kaura LGA irrigation impoundment.',
    },

    # ══ KANO STATE DAMS ═════════════════════════════════════════════════════════
    {
        'name': 'Kano Municipal Dam (Tamburawa)',
        'river_basin': 'Challawa',
        'state': 'Kano',
        'country': 'Nigeria',
        'latitude': 12.0500,
        'longitude': 8.6333,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1978,
        'purpose': 'Water supply for Kano metropolitan area',
        'risk_level': 'low',
        'downstream_states': 'Kano',
        'data_source': 'Kano State Water Board',
        'notes': 'Tamburawa water treatment intake structure. Part of Kano water supply system.',
    },
    {
        'name': 'Gari Dam (Kano)',
        'river_basin': 'Hadejia tributary',
        'state': 'Kano',
        'country': 'Nigeria',
        'latitude': 11.8000,
        'longitude': 9.2000,
        'capacity_mcm': 18,
        'height_m': 11,
        'year_completed': 1989,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Kano',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Gari LGA irrigation scheme.',
    },
    {
        'name': 'Garun Mallam Dam',
        'river_basin': 'Challawa tributary',
        'state': 'Kano',
        'country': 'Nigeria',
        'latitude': 11.7500,
        'longitude': 8.7000,
        'capacity_mcm': 12,
        'height_m': 9,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kano',
        'data_source': 'Hadejia-Jamaare RBDA',
        'notes': 'Small irrigation impoundment, Kano.',
    },

    # ══ PLATEAU STATE DAMS ══════════════════════════════════════════════════════
    {
        'name': 'Kurra Dam',
        'river_basin': 'Richa River',
        'state': 'Plateau',
        'country': 'Nigeria',
        'latitude': 9.6833,
        'longitude': 8.7000,
        'capacity_mcm': 20,
        'height_m': 14,
        'year_completed': 1975,
        'purpose': 'Water supply for Bukuru/Rantya',
        'risk_level': 'low',
        'downstream_states': 'Plateau',
        'data_source': 'Plateau State Water Board',
        'notes': 'Historical water supply for Bukuru area, Jos South.',
    },
    {
        'name': 'Jebbu Dam',
        'river_basin': 'Gishiri River',
        'state': 'Plateau',
        'country': 'Nigeria',
        'latitude': 9.7667,
        'longitude': 9.1333,
        'capacity_mcm': 18,
        'height_m': 12,
        'year_completed': 1982,
        'purpose': 'Water supply (Bukuru supplementary)',
        'risk_level': 'low',
        'downstream_states': 'Plateau',
        'data_source': 'Plateau State Water Board',
        'notes': 'Supplementary water supply, Plateau State.',
    },
    {
        'name': 'Sha Dam (Shen)',
        'river_basin': 'Wamba',
        'state': 'Plateau',
        'country': 'Nigeria',
        'latitude': 9.5500,
        'longitude': 9.2500,
        'capacity_mcm': 40,
        'height_m': 18,
        'year_completed': 1988,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Plateau',
        'data_source': 'Plateau State / Lower Benue RBDA',
        'notes': 'Shendam LGA irrigation scheme.',
    },
    {
        'name': 'Barkin Ladi Dam',
        'river_basin': 'Delimi River',
        'state': 'Plateau',
        'country': 'Nigeria',
        'latitude': 9.5000,
        'longitude': 8.9000,
        'capacity_mcm': 30,
        'height_m': 16,
        'year_completed': 1980,
        'purpose': 'Water supply for mining activities, irrigation',
        'risk_level': 'medium',
        'downstream_states': 'Plateau',
        'data_source': 'Plateau State Water Board / Mining Cadastre Office',
        'notes': 'Barkin Ladi tin mining area dam. Risk of acid mine drainage in flood events.',
    },
    {
        'name': 'Bokkos Dam',
        'river_basin': 'Wamba tributary',
        'state': 'Plateau',
        'country': 'Nigeria',
        'latitude': 9.3000,
        'longitude': 8.9500,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1989,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Plateau',
        'data_source': 'Plateau State / Lower Benue RBDA',
        'notes': 'Bokkos LGA small irrigation dam.',
    },
    {
        'name': 'Kanang Dam',
        'river_basin': 'Kaduna headwater',
        'state': 'Plateau',
        'country': 'Nigeria',
        'latitude': 9.2500,
        'longitude': 9.5000,
        'capacity_mcm': 25,
        'height_m': 14,
        'year_completed': 1987,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Plateau',
        'data_source': 'Plateau State ADP',
        'notes': 'Kanke LGA irrigation dam on Kaduna River headwater.',
    },

    # ══ ANAMBRA-IMO RBDA — ADDITIONAL ══════════════════════════════════════════
    {
        'name': 'Idemili Dam',
        'river_basin': 'Idemili River',
        'state': 'Anambra',
        'country': 'Nigeria',
        'latitude': 6.2167,
        'longitude': 6.9833,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1985,
        'purpose': 'Water supply for Onitsha supplementary',
        'risk_level': 'low',
        'downstream_states': 'Anambra',
        'data_source': 'Anambra-Imo RBDA / Anambra State Water Corp',
        'notes': 'Supplementary water supply for Onitsha and Nnewi axis.',
    },
    {
        'name': 'Njaba Dam',
        'river_basin': 'Njaba River',
        'state': 'Imo',
        'country': 'Nigeria',
        'latitude': 5.7333,
        'longitude': 6.9333,
        'capacity_mcm': 20,
        'height_m': 12,
        'year_completed': 1986,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Imo',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Njaba River irrigation and water supply scheme.',
    },
    {
        'name': 'Nworie Dam',
        'river_basin': 'Nworie River',
        'state': 'Imo',
        'country': 'Nigeria',
        'latitude': 5.5167,
        'longitude': 7.0833,
        'capacity_mcm': 10,
        'height_m': 9,
        'year_completed': 1982,
        'purpose': 'Water supply for Owerri (historic)',
        'risk_level': 'low',
        'downstream_states': 'Imo',
        'data_source': 'Anambra-Imo RBDA / Imo State',
        'notes': 'Historic water supply structure for Owerri.',
    },
    {
        'name': 'Nsu Dam',
        'river_basin': 'Imo River tributary',
        'state': 'Imo',
        'country': 'Nigeria',
        'latitude': 5.7000,
        'longitude': 7.4000,
        'capacity_mcm': 18,
        'height_m': 11,
        'year_completed': 1991,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Imo',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Ehime Mbano LGA small irrigation impoundment.',
    },
    {
        'name': 'Ele-Ala Dam',
        'river_basin': 'Imo River',
        'state': 'Imo',
        'country': 'Nigeria',
        'latitude': 5.6167,
        'longitude': 7.2833,
        'capacity_mcm': 12,
        'height_m': 10,
        'year_completed': 1987,
        'purpose': 'Water supply',
        'risk_level': 'low',
        'downstream_states': 'Imo',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Small water supply dam, Imo State.',
    },
    {
        'name': 'Agwa Dam',
        'river_basin': 'Imo River tributary',
        'state': 'Imo',
        'country': 'Nigeria',
        'latitude': 5.5167,
        'longitude': 6.8500,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1989,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Imo',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Oguta LGA area irrigation dam.',
    },
    {
        'name': 'Umuma Dam',
        'river_basin': 'Cross River headwater',
        'state': 'Abia',
        'country': 'Nigeria',
        'latitude': 5.6500,
        'longitude': 7.7500,
        'capacity_mcm': 12,
        'height_m': 10,
        'year_completed': 1990,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Abia',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Small irrigation impoundment, Abia State.',
    },
    {
        'name': 'Arochukwu Dam',
        'river_basin': 'Cross River tributary',
        'state': 'Abia',
        'country': 'Nigeria',
        'latitude': 5.3667,
        'longitude': 7.9333,
        'capacity_mcm': 15,
        'height_m': 11,
        'year_completed': 1992,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Abia',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Arochukwu area water supply and irrigation.',
    },
    {
        'name': 'Ezza Dam',
        'river_basin': 'Cross River headwater',
        'state': 'Ebonyi',
        'country': 'Nigeria',
        'latitude': 6.3500,
        'longitude': 8.1500,
        'capacity_mcm': 20,
        'height_m': 13,
        'year_completed': 1994,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Ebonyi',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Ezza South LGA irrigation scheme.',
    },
    {
        'name': 'Ishielu Dam',
        'river_basin': 'Cross River headwater',
        'state': 'Ebonyi',
        'country': 'Nigeria',
        'latitude': 6.5000,
        'longitude': 8.0000,
        'capacity_mcm': 18,
        'height_m': 12,
        'year_completed': 1993,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Ebonyi',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Ishielu LGA irrigation scheme, Ebonyi.',
    },
    {
        'name': 'Ohaukwu Dam',
        'river_basin': 'Ebonyi River',
        'state': 'Ebonyi',
        'country': 'Nigeria',
        'latitude': 6.8500,
        'longitude': 8.1000,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1991,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Ebonyi',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Ohaukwu LGA small irrigation impoundment.',
    },
    {
        'name': 'Enugu Ezike Dam',
        'river_basin': 'Anambra headwater',
        'state': 'Enugu',
        'country': 'Nigeria',
        'latitude': 6.9833,
        'longitude': 7.4500,
        'capacity_mcm': 18,
        'height_m': 12,
        'year_completed': 1990,
        'purpose': 'Water supply for Igbo-Eze area',
        'risk_level': 'low',
        'downstream_states': 'Enugu',
        'data_source': 'Anambra-Imo RBDA / Enugu State Water Corp',
        'notes': 'Water supply dam for northern Enugu communities.',
    },
    {
        'name': 'Oji River Dam',
        'river_basin': 'Oji River',
        'state': 'Enugu',
        'country': 'Nigeria',
        'latitude': 6.4000,
        'longitude': 7.3500,
        'capacity_mcm': 12,
        'height_m': 9,
        'year_completed': 1975,
        'purpose': 'Water supply for Oji River township',
        'risk_level': 'low',
        'downstream_states': 'Enugu',
        'data_source': 'Anambra-Imo RBDA',
        'notes': 'Historical Oji River power station and water supply structure.',
    },

    # ══ BENIN-OWENA RBDA — ADDITIONAL ══════════════════════════════════════════
    {
        'name': 'Osse Dam',
        'river_basin': 'Osse River',
        'state': 'Edo',
        'country': 'Nigeria',
        'latitude': 6.4500,
        'longitude': 5.9833,
        'capacity_mcm': 30,
        'height_m': 15,
        'year_completed': 1988,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Edo',
        'data_source': 'Benin-Owena RBDA / Edo State',
        'notes': 'Osse River water supply structure.',
    },
    {
        'name': 'Ovia Dam',
        'river_basin': 'Ovia River',
        'state': 'Edo',
        'country': 'Nigeria',
        'latitude': 6.6333,
        'longitude': 5.4333,
        'capacity_mcm': 60,
        'height_m': 20,
        'year_completed': 1985,
        'purpose': 'Water supply for Benin City, irrigation',
        'risk_level': 'medium',
        'downstream_states': 'Edo',
        'data_source': 'Benin-Owena RBDA / Edo State Water Corporation',
        'notes': 'Major supplementary water supply for Benin City metropolitan area.',
    },
    {
        'name': 'Ethiope Dam',
        'river_basin': 'Ethiope River',
        'state': 'Delta',
        'country': 'Nigeria',
        'latitude': 5.5167,
        'longitude': 5.9667,
        'capacity_mcm': 25,
        'height_m': 12,
        'year_completed': 1990,
        'purpose': 'Water supply for Abraka/Ughelli',
        'risk_level': 'low',
        'downstream_states': 'Delta',
        'data_source': 'Benin-Owena RBDA / Delta State Water Board',
        'notes': 'Ethiope River impoundment for Delta State water supply.',
    },
    {
        'name': 'Siluko Dam',
        'river_basin': 'Siluko River',
        'state': 'Edo',
        'country': 'Nigeria',
        'latitude': 6.5000,
        'longitude': 5.6000,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1987,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Edo',
        'data_source': 'Benin-Owena RBDA',
        'notes': 'Small water supply and irrigation dam, Edo State.',
    },
    {
        'name': 'Omobos Dam (Ondo)',
        'river_basin': 'Omobos River',
        'state': 'Ondo',
        'country': 'Nigeria',
        'latitude': 6.9000,
        'longitude': 5.0000,
        'capacity_mcm': 20,
        'height_m': 13,
        'year_completed': 1989,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Ondo',
        'data_source': 'Benin-Owena RBDA / Ondo State',
        'notes': 'Local irrigation scheme, Ondo State.',
    },
    {
        'name': 'Oni Dam',
        'river_basin': 'Oni River',
        'state': 'Ondo',
        'country': 'Nigeria',
        'latitude': 7.1833,
        'longitude': 5.1167,
        'capacity_mcm': 18,
        'height_m': 12,
        'year_completed': 1991,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Ondo',
        'data_source': 'Benin-Owena RBDA',
        'notes': 'Ondo State small irrigation and water supply dam.',
    },
    {
        'name': 'Tunbi Dam (Ekiti)',
        'river_basin': 'Ose River',
        'state': 'Ekiti',
        'country': 'Nigeria',
        'latitude': 7.3500,
        'longitude': 5.2500,
        'capacity_mcm': 22,
        'height_m': 14,
        'year_completed': 1990,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Ekiti',
        'data_source': 'Benin-Owena RBDA / Ekiti State',
        'notes': 'Ekiti State supplementary water supply and irrigation.',
    },
    {
        'name': 'Ero Dam (Ekiti)',
        'river_basin': 'Ero River',
        'state': 'Ekiti',
        'country': 'Nigeria',
        'latitude': 7.7500,
        'longitude': 5.4500,
        'capacity_mcm': 140,
        'height_m': 30,
        'year_completed': 2009,
        'purpose': 'Water supply for Ado-Ekiti, Ikole and Iyin-Ekiti, irrigation',
        'risk_level': 'medium',
        'downstream_states': 'Ekiti, Kogi',
        'data_source': 'Benin-Owena RBDA / Ekiti State Water Corporation',
        'notes': 'Modern dam providing water supply to several Ekiti cities. Largest dam in Ekiti State.',
    },
    {
        'name': 'Egbe Dam (Kogi)',
        'river_basin': 'Ose River',
        'state': 'Kogi',
        'country': 'Nigeria',
        'latitude': 8.0833,
        'longitude': 5.5833,
        'capacity_mcm': 45,
        'height_m': 18,
        'year_completed': 1983,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Kogi',
        'data_source': 'Benin-Owena RBDA / Kogi State',
        'notes': 'Yagba West LGA water supply dam on Ose River.',
    },

    # ══ OGUN-OSUN RBDA — ADDITIONAL ════════════════════════════════════════════
    {
        'name': 'Ona River Dam',
        'river_basin': 'Ona River',
        'state': 'Oyo',
        'country': 'Nigeria',
        'latitude': 7.3500,
        'longitude': 3.9333,
        'capacity_mcm': 20,
        'height_m': 12,
        'year_completed': 1978,
        'purpose': 'Water supply for Ibadan supplementary',
        'risk_level': 'medium',
        'downstream_states': 'Oyo',
        'data_source': 'Ogun-Osun RBDA / OYSWATER',
        'notes': 'Ona River impoundment supplementing Ibadan water supply. Flash flooding below dam when full.',
    },
    {
        'name': 'Ikere Gorge Saddle Dam',
        'river_basin': 'Ogun',
        'state': 'Ogun',
        'country': 'Nigeria',
        'latitude': 7.5333,
        'longitude': 3.6500,
        'capacity_mcm': 50,
        'height_m': 18,
        'year_completed': 1983,
        'purpose': 'Auxiliary dam to contain Oyan reservoir',
        'risk_level': 'medium',
        'downstream_states': 'Ogun, Lagos',
        'data_source': 'Ogun-Osun RBDA',
        'notes': 'Saddle dam forming part of the Oyan Dam reservoir containment system.',
    },
    {
        'name': 'Omi Dam (Osun)',
        'river_basin': 'Osun tributary',
        'state': 'Osun',
        'country': 'Nigeria',
        'latitude': 7.4500,
        'longitude': 4.3833,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1985,
        'purpose': 'Water supply for Ile-Ife supplementary',
        'risk_level': 'low',
        'downstream_states': 'Osun',
        'data_source': 'Ogun-Osun RBDA',
        'notes': 'Ile-Ife supplementary water supply structure.',
    },
    {
        'name': 'Esa-Oke Dam',
        'river_basin': 'Osun headwater',
        'state': 'Osun',
        'country': 'Nigeria',
        'latitude': 7.5667,
        'longitude': 4.8000,
        'capacity_mcm': 22,
        'height_m': 14,
        'year_completed': 1987,
        'purpose': 'Water supply for Esa-Oke township',
        'risk_level': 'low',
        'downstream_states': 'Osun',
        'data_source': 'Ogun-Osun RBDA / Osun State Water Corp',
        'notes': 'Obokun LGA water supply dam.',
    },
    {
        'name': 'Iwo Dam',
        'river_basin': 'Oba River',
        'state': 'Osun',
        'country': 'Nigeria',
        'latitude': 7.6333,
        'longitude': 4.1833,
        'capacity_mcm': 18,
        'height_m': 12,
        'year_completed': 1989,
        'purpose': 'Water supply for Iwo city',
        'risk_level': 'low',
        'downstream_states': 'Osun',
        'data_source': 'Ogun-Osun RBDA',
        'notes': 'Iwo town water supply dam.',
    },
    {
        'name': 'Ago-Are Dam',
        'river_basin': 'Ogun tributary',
        'state': 'Oyo',
        'country': 'Nigeria',
        'latitude': 8.6500,
        'longitude': 3.5167,
        'capacity_mcm': 25,
        'height_m': 13,
        'year_completed': 1991,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Oyo',
        'data_source': 'Ogun-Osun RBDA',
        'notes': 'Atisbo LGA irrigation scheme.',
    },
    {
        'name': 'Kamuku Dam (Oyo)',
        'river_basin': 'Kamuku River',
        'state': 'Oyo',
        'country': 'Nigeria',
        'latitude': 8.2000,
        'longitude': 3.9500,
        'capacity_mcm': 30,
        'height_m': 14,
        'year_completed': 1988,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Oyo',
        'data_source': 'Ogun-Osun RBDA',
        'notes': 'Iwajowa LGA irrigation and water supply dam.',
    },
    {
        'name': 'Awe Ewi Dam (Ekiti)',
        'river_basin': 'Owena tributary',
        'state': 'Ekiti',
        'country': 'Nigeria',
        'latitude': 7.4833,
        'longitude': 5.2000,
        'capacity_mcm': 10,
        'height_m': 9,
        'year_completed': 1986,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Ekiti',
        'data_source': 'Benin-Owena RBDA',
        'notes': 'Small water supply dam, Ekiti State.',
    },

    # ══ LOWER NIGER RBDA — ADDITIONAL ══════════════════════════════════════════
    {
        'name': 'Kiri Dam Tail-Channel Structure',
        'river_basin': 'Gongola',
        'state': 'Adamawa',
        'country': 'Nigeria',
        'latitude': 9.7167,
        'longitude': 12.0833,
        'capacity_mcm': 80,
        'height_m': 12,
        'year_completed': 1985,
        'purpose': 'Irrigation distribution, flood control below Kiri Dam',
        'risk_level': 'low',
        'downstream_states': 'Adamawa',
        'data_source': 'Lower Niger RBDA',
        'notes': 'Irrigation distribution weir below Kiri Dam.',
    },
    {
        'name': 'Shelleng Dam',
        'river_basin': 'Gongola tributary',
        'state': 'Adamawa',
        'country': 'Nigeria',
        'latitude': 9.5000,
        'longitude': 11.9500,
        'capacity_mcm': 20,
        'height_m': 12,
        'year_completed': 1990,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Adamawa',
        'data_source': 'Lower Niger RBDA',
        'notes': 'Shelleng LGA irrigation scheme.',
    },
    {
        'name': 'Mayo Ine Dam',
        'river_basin': 'Mayo Ine',
        'state': 'Adamawa',
        'country': 'Nigeria',
        'latitude': 9.2500,
        'longitude': 12.7500,
        'capacity_mcm': 18,
        'height_m': 11,
        'year_completed': 1988,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Adamawa',
        'data_source': 'Lower Niger RBDA / Upper Benue RBDA',
        'notes': 'Small irrigation impoundment, Adamawa.',
    },
    {
        'name': 'Holma Dam',
        'river_basin': 'Benue tributary',
        'state': 'Adamawa',
        'country': 'Nigeria',
        'latitude': 9.0833,
        'longitude': 12.4667,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1989,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Adamawa',
        'data_source': 'Upper Benue RBDA',
        'notes': 'Yola North area small irrigation scheme.',
    },
    {
        'name': 'Beti Dam',
        'river_basin': 'Gongola',
        'state': 'Gombe',
        'country': 'Nigeria',
        'latitude': 10.0833,
        'longitude': 11.7833,
        'capacity_mcm': 30,
        'height_m': 14,
        'year_completed': 1994,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Gombe',
        'data_source': 'Lower Niger RBDA / Gombe State',
        'notes': 'Balanga LGA irrigation scheme on Gongola River.',
    },
    {
        'name': 'Pempe Dam',
        'river_basin': 'Pempe River',
        'state': 'Gombe',
        'country': 'Nigeria',
        'latitude': 9.8833,
        'longitude': 11.5667,
        'capacity_mcm': 18,
        'height_m': 11,
        'year_completed': 1991,
        'purpose': 'Irrigation',
        'risk_level': 'low',
        'downstream_states': 'Gombe',
        'data_source': 'Lower Niger RBDA',
        'notes': 'Kaltungo area irrigation impoundment.',
    },
    {
        'name': 'Pindiga Dam',
        'river_basin': 'Gongola tributary',
        'state': 'Gombe',
        'country': 'Nigeria',
        'latitude': 10.0167,
        'longitude': 10.9333,
        'capacity_mcm': 22,
        'height_m': 12,
        'year_completed': 1993,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Gombe',
        'data_source': 'Lower Niger RBDA',
        'notes': 'Akko LGA water supply and irrigation.',
    },

    # ══ CROSS RIVER BASIN DA — ADDITIONAL ══════════════════════════════════════
    {
        'name': 'Oban Hills Dam',
        'river_basin': 'Cross River',
        'state': 'Cross River',
        'country': 'Nigeria',
        'latitude': 5.4500,
        'longitude': 8.6000,
        'capacity_mcm': 10,
        'height_m': 10,
        'year_completed': 1990,
        'purpose': 'Water supply, eco-tourism water management',
        'risk_level': 'low',
        'downstream_states': 'Cross River',
        'data_source': 'Cross River Basin Development Authority',
        'notes': 'Oban Hills forest area water management structure. Eco-tourism zone.',
    },
    {
        'name': 'Itigidi Dam',
        'river_basin': 'Cross River',
        'state': 'Cross River',
        'country': 'Nigeria',
        'latitude': 5.6167,
        'longitude': 8.2167,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1988,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Cross River',
        'data_source': 'Cross River Basin Development Authority',
        'notes': 'Abi LGA small irrigation scheme.',
    },
    {
        'name': 'Odukpani Dam',
        'river_basin': 'Cross River',
        'state': 'Cross River',
        'country': 'Nigeria',
        'latitude': 5.0833,
        'longitude': 8.1500,
        'capacity_mcm': 20,
        'height_m': 12,
        'year_completed': 1992,
        'purpose': 'Water supply (Calabar satellite)',
        'risk_level': 'low',
        'downstream_states': 'Cross River',
        'data_source': 'Cross River Basin Development Authority / CRS Water Board',
        'notes': 'Supplementary water supply for Calabar metropolitan area.',
    },
    {
        'name': 'Biase Dam',
        'river_basin': 'Cross River',
        'state': 'Cross River',
        'country': 'Nigeria',
        'latitude': 5.2500,
        'longitude': 8.1000,
        'capacity_mcm': 18,
        'height_m': 11,
        'year_completed': 1990,
        'purpose': 'Irrigation, water supply',
        'risk_level': 'low',
        'downstream_states': 'Cross River',
        'data_source': 'Cross River Basin Development Authority',
        'notes': 'Biase LGA irrigation and water supply.',
    },

    # ══ SOUTH-SOUTH SMALL DAMS ══════════════════════════════════════════════════
    {
        'name': 'Imo River Dam (Akwa Ibom)',
        'river_basin': 'Imo River',
        'state': 'Akwa Ibom',
        'country': 'Nigeria',
        'latitude': 4.9500,
        'longitude': 7.4500,
        'capacity_mcm': 15,
        'height_m': 10,
        'year_completed': 1988,
        'purpose': 'Water supply, irrigation',
        'risk_level': 'low',
        'downstream_states': 'Akwa Ibom',
        'data_source': 'Anambra-Imo RBDA / Akwa Ibom State Water Board',
        'notes': 'Imo River impoundment for northern Akwa Ibom water supply.',
    },
    {
        'name': 'Ikot Abasi Tidal Control Weir',
        'river_basin': 'Imo River estuary',
        'state': 'Akwa Ibom',
        'country': 'Nigeria',
        'latitude': 4.5667,
        'longitude': 7.5667,
        'capacity_mcm': 5,
        'height_m': 5,
        'year_completed': 1980,
        'purpose': 'Tidal control, water supply',
        'risk_level': 'low',
        'downstream_states': 'Akwa Ibom',
        'data_source': 'Akwa Ibom State Water Board',
        'notes': 'Tidal control structure at Imo River estuary. Prevents salt water intrusion.',
    },
    {
        'name': 'Ndian Dam (Cross River)',
        'river_basin': 'Ndian River',
        'state': 'Cross River',
        'country': 'Nigeria',
        'latitude': 4.8833,
        'longitude': 8.8000,
        'capacity_mcm': 12,
        'height_m': 9,
        'year_completed': 1991,
        'purpose': 'Water supply',
        'risk_level': 'low',
        'downstream_states': 'Cross River',
        'data_source': 'Cross River Basin Development Authority',
        'notes': 'Remote area water supply dam, southern Cross River.',
    },
]


# ═══════════════════════════════════════════════════════════════════════════════
#  ADDITIONAL FLOOD ZONES — SECOND EXPANSION
#  Targeting remaining uncovered LGAs and adding detail to existing states.
#  Special focus on: Sokoto basin, Lake Chad fringe, Plateau escarpment,
#  Southeast gully-flood zones, and coastal sea-level rise watch zones.
# ═══════════════════════════════════════════════════════════════════════════════

ADDITIONAL_FLOOD_ZONES2 = [

    # ── SOKOTO STATE ─────────────────────────────────────────────────────────────
    {
        'zone_name': 'Sokoto-Rima Confluence Flood Plain',
        'risk_level': 'very_high',
        'state': 'Sokoto',
        'lga': 'Sokoto South',
        'min_lat': 13.0000, 'max_lat': 13.1500,
        'min_lng': 5.1500, 'max_lng': 5.3500,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024 / Sokoto-Rima RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Sokoto city sits at the confluence of Sokoto and Rima Rivers. Annual severe flooding affecting residential and agricultural areas.',
    },
    {
        'zone_name': 'Isa-Sabon Birni Rima Plain',
        'risk_level': 'high',
        'state': 'Sokoto',
        'lga': 'Isa',
        'min_lat': 12.9000, 'max_lat': 13.1000,
        'min_lng': 6.3000, 'max_lng': 6.6500,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Rima River plain communities. Annual flooding displacing farming households.',
    },
    {
        'zone_name': 'Tangaza Goronyo Reservoir Fringe',
        'risk_level': 'medium',
        'state': 'Sokoto',
        'lga': 'Tangaza',
        'min_lat': 13.3000, 'max_lat': 13.5500,
        'min_lng': 5.3000, 'max_lng': 5.8000,
        'flood_type': 'combined',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024 / Sokoto-Rima RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Communities near Goronyo Dam reservoir fringe. Risk of dam overflow during heavy rainfall.',
    },

    # ── ZAMFARA STATE ─────────────────────────────────────────────────────────────
    {
        'zone_name': 'Gusau-Bungudu Urban Flood Zone',
        'risk_level': 'high',
        'state': 'Zamfara',
        'lga': 'Gusau',
        'min_lat': 12.1500, 'max_lat': 12.2500,
        'min_lng': 6.6500, 'max_lng': 6.8000,
        'flood_type': 'urban',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2024 / Zamfara State NEMA',
        'last_major_flood_year': 2022,
        'notes': 'Gusau, Zamfara State capital, listed for urban flooding. Kwatarkwashi Dam releases compound natural flooding.',
    },
    {
        'zone_name': 'Maru-Tsafe Rima Tributary Zone',
        'risk_level': 'medium',
        'state': 'Zamfara',
        'lga': 'Maru',
        'min_lat': 12.0000, 'max_lat': 12.3000,
        'min_lng': 7.3000, 'max_lng': 7.6000,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Seasonal flooding in Maru-Tsafe area from Rima River tributaries.',
    },
    {
        'zone_name': 'Kaura Namoda Flood Corridor',
        'risk_level': 'medium',
        'state': 'Zamfara',
        'lga': 'Kaura-Namoda',
        'min_lat': 12.5000, 'max_lat': 12.7000,
        'min_lng': 6.5000, 'max_lng': 6.8000,
        'flood_type': 'flash',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Flash flooding from seasonal watercourses in Kaura Namoda area.',
    },

    # ── KATSINA STATE ─────────────────────────────────────────────────────────────
    {
        'zone_name': 'Katsina Urban Flood Zone',
        'risk_level': 'high',
        'state': 'Katsina',
        'lga': 'Katsina',
        'min_lat': 12.9500, 'max_lat': 13.0500,
        'min_lng': 7.5500, 'max_lng': 7.7000,
        'flood_type': 'urban',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2023 / Katsina State NEMA',
        'last_major_flood_year': 2022,
        'notes': 'Katsina city listed by NIHSA for urban flash flooding. State capital with inadequate drainage.',
    },
    {
        'zone_name': 'Dutsin-Ma Katsina River Flood Zone',
        'risk_level': 'medium',
        'state': 'Katsina',
        'lga': 'Dutsin-Ma',
        'min_lat': 12.3500, 'max_lat': 12.5500,
        'min_lng': 7.4000, 'max_lng': 7.6500,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Katsina River flooding in Dutsin-Ma LGA.',
    },
    {
        'zone_name': 'Daura Sabuwa Flash Flood Zone',
        'risk_level': 'medium',
        'state': 'Katsina',
        'lga': 'Daura',
        'min_lat': 13.0000, 'max_lat': 13.1500,
        'min_lng': 8.2000, 'max_lng': 8.4000,
        'flood_type': 'flash',
        'peak_months': 'July-August',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Sahel zone flash flooding. Daura — historic emirate, modern commercial centre.',
    },

    # ── YOBE STATE ────────────────────────────────────────────────────────────────
    {
        'zone_name': 'Bade-Machina Hadejia Plain',
        'risk_level': 'high',
        'state': 'Yobe',
        'lga': 'Bade',
        'min_lat': 12.7000, 'max_lat': 12.9000,
        'min_lng': 10.7000, 'max_lng': 11.1500,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024 / Chad Basin DA',
        'last_major_flood_year': 2022,
        'notes': 'Hadejia-Nguru wetland fringe. Seasonal flooding displacing fishing and farming communities.',
    },
    {
        'zone_name': 'Jakusko Komadugu Flood Plain',
        'risk_level': 'medium',
        'state': 'Yobe',
        'lga': 'Jakusko',
        'min_lat': 12.0000, 'max_lat': 12.2500,
        'min_lng': 11.3000, 'max_lng': 11.7000,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Komadugu Gana River floodplain. Annual agricultural flooding.',
    },

    # ── BORNO STATE ───────────────────────────────────────────────────────────────
    {
        'zone_name': 'Jere-Mafa Ngadda Plain',
        'risk_level': 'very_high',
        'state': 'Borno',
        'lga': 'Jere',
        'min_lat': 11.7500, 'max_lat': 11.9000,
        'min_lng': 13.1000, 'max_lng': 13.3500,
        'flood_type': 'dam_breach',
        'peak_months': 'August-October',
        'data_source': 'NEMA / Borno SEMA / NIHSA AFO 2024',
        'last_major_flood_year': 2024,
        'notes': 'Jere LGA is the area of Maiduguri worst affected by Alau Dam overflow. Communities along Ngadda River face annual flooding risk and are in the direct dam-breach inundation path.',
    },
    {
        'zone_name': 'Damboa-Biu Plateau Flash Flood Zone',
        'risk_level': 'medium',
        'state': 'Borno',
        'lga': 'Damboa',
        'min_lat': 11.0500, 'max_lat': 11.3500,
        'min_lng': 12.7000, 'max_lng': 13.1000,
        'flood_type': 'flash',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Plateau escarpment flash flooding. Area previously affected by insurgency.',
    },

    # ── KEBBI STATE ───────────────────────────────────────────────────────────────
    {
        'zone_name': 'Argungu-Gwandu Niger River Floodplain',
        'risk_level': 'very_high',
        'state': 'Kebbi',
        'lga': 'Argungu',
        'min_lat': 12.7000, 'max_lat': 12.9500,
        'min_lng': 4.4000, 'max_lng': 4.7000,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024 / Sokoto-Rima RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Argungu sits on the Kebbi (Rima) River. Annual flooding of historic emirate and famous fishing festival grounds.',
    },
    {
        'zone_name': 'Yauri Niger River Communities',
        'risk_level': 'high',
        'state': 'Kebbi',
        'lga': 'Yauri',
        'min_lat': 10.7500, 'max_lat': 11.0000,
        'min_lng': 4.5000, 'max_lng': 4.9500,
        'flood_type': 'riverine',
        'peak_months': 'September-October',
        'data_source': 'NIHSA AFO 2024 / Upper Niger RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Downstream of Kainji Dam. When Kainji releases are uncoordinated, Yauri communities experience severe flooding.',
    },

    # ── NIGER STATE ───────────────────────────────────────────────────────────────
    {
        'zone_name': 'Agaie-Lapai Niger River Basin',
        'risk_level': 'very_high',
        'state': 'Niger',
        'lga': 'Agaie',
        'min_lat': 8.9000, 'max_lat': 9.2000,
        'min_lng': 5.8000, 'max_lng': 6.2000,
        'flood_type': 'riverine',
        'peak_months': 'September-November',
        'data_source': 'NIHSA AFO 2024 / Upper Niger RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Niger River floodplain communities between Jebba and the confluence. Severely affected in 2022.',
    },
    {
        'zone_name': 'Lavun-Gbako Niger River Bank',
        'risk_level': 'very_high',
        'state': 'Niger',
        'lga': 'Lavun',
        'min_lat': 8.5000, 'max_lat': 8.9000,
        'min_lng': 5.5000, 'max_lng': 5.9000,
        'flood_type': 'riverine',
        'peak_months': 'September-November',
        'data_source': 'NIHSA AFO 2024 / Presidential Flood Committee 2022',
        'last_major_flood_year': 2022,
        'notes': 'River Niger bank communities. Part of the 2022 catastrophic flood corridor.',
    },
    {
        'zone_name': 'Mokwa-Katcha Niger Flood Plain',
        'risk_level': 'high',
        'state': 'Niger',
        'lga': 'Mokwa',
        'min_lat': 9.2000, 'max_lat': 9.4500,
        'min_lng': 5.0000, 'max_lng': 5.4000,
        'flood_type': 'riverine',
        'peak_months': 'September-October',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Mokwa sits on the Niger River. Annual flooding downstream of Jebba Dam.',
    },
    {
        'zone_name': 'Wushishi Kaduna River Plain',
        'risk_level': 'high',
        'state': 'Niger',
        'lga': 'Wushishi',
        'min_lat': 10.0500, 'max_lat': 10.3000,
        'min_lng': 6.1000, 'max_lng': 6.4500,
        'flood_type': 'riverine',
        'peak_months': 'August-October',
        'data_source': 'NIHSA AFO 2024 / Upper Niger RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Kaduna River plain below Shiroro Dam. Risk of flood when Shiroro releases.',
    },

    # ── OYO STATE ─────────────────────────────────────────────────────────────────
    {
        'zone_name': 'Oyo-Atiba Urban Flood Zone',
        'risk_level': 'medium',
        'state': 'Oyo',
        'lga': 'Oyo East',
        'min_lat': 7.8000, 'max_lat': 7.9200,
        'min_lng': 3.9000, 'max_lng': 4.0200,
        'flood_type': 'urban',
        'peak_months': 'June-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Oyo town urban flooding. Ogun-Osun basin tributary overflow.',
    },
    {
        'zone_name': 'Saki-Oorelope River Flood Zone',
        'risk_level': 'medium',
        'state': 'Oyo',
        'lga': 'Saki West',
        'min_lat': 8.6500, 'max_lat': 8.8000,
        'min_lng': 3.3500, 'max_lng': 3.5500,
        'flood_type': 'riverine',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Ogun River headwater flooding in northern Oyo.',
    },

    # ── KWARA STATE ───────────────────────────────────────────────────────────────
    {
        'zone_name': 'Lafiagi-Kaiama Niger River Fringe',
        'risk_level': 'very_high',
        'state': 'Kwara',
        'lga': 'Lafiagi',
        'min_lat': 8.8500, 'max_lat': 9.1000,
        'min_lng': 5.3500, 'max_lng': 5.7000,
        'flood_type': 'riverine',
        'peak_months': 'September-November',
        'data_source': 'NIHSA AFO 2024 / OCHA 2022',
        'last_major_flood_year': 2022,
        'notes': 'Lafiagi is a major Niger River town severely flooded annually. Communities repeatedly displaced.',
    },
    {
        'zone_name': 'Ifelodun-Offa Niger Tributary Zone',
        'risk_level': 'medium',
        'state': 'Kwara',
        'lga': 'Ifelodun',
        'min_lat': 8.0000, 'max_lat': 8.2500,
        'min_lng': 4.8000, 'max_lng': 5.1000,
        'flood_type': 'riverine',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Niger River tributary flooding in central Kwara.',
    },

    # ── KOGI STATE ────────────────────────────────────────────────────────────────
    {
        'zone_name': 'Koton Karfe Niger-Benue Approach Zone',
        'risk_level': 'critical',
        'state': 'Kogi',
        'lga': 'Kogi',
        'min_lat': 7.8500, 'max_lat': 8.0500,
        'min_lng': 6.7500, 'max_lng': 6.9500,
        'flood_type': 'riverine',
        'peak_months': 'September-November',
        'data_source': 'NIHSA AFO 2024 / OCHA 2024',
        'last_major_flood_year': 2024,
        'notes': 'Koton Karfe is directly upstream of the Lokoja confluence — when both rivers peak, this area floods catastrophically first.',
    },
    {
        'zone_name': 'Mopamuro-Ijumu Niger Flood Corridor',
        'risk_level': 'high',
        'state': 'Kogi',
        'lga': 'Mopamuro',
        'min_lat': 7.9500, 'max_lat': 8.3000,
        'min_lng': 5.9500, 'max_lng': 6.3000,
        'flood_type': 'riverine',
        'peak_months': 'September-November',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Niger River tributaries in western Kogi flooding annually.',
    },
    {
        'zone_name': 'Bassa-Igalamela Idah Flood Zone',
        'risk_level': 'very_high',
        'state': 'Kogi',
        'lga': 'Bassa',
        'min_lat': 7.6500, 'max_lat': 7.9500,
        'min_lng': 6.9000, 'max_lng': 7.2500,
        'flood_type': 'riverine',
        'peak_months': 'August-November',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Bassa-Igalamela corridor along lower Niger River — annual severe flooding.',
    },

    # ── NASARAWA STATE ────────────────────────────────────────────────────────────
    {
        'zone_name': 'Nassarawa Eggon Benue Headwater',
        'risk_level': 'medium',
        'state': 'Nasarawa',
        'lga': 'Nassarawa Eggon',
        'min_lat': 8.5500, 'max_lat': 8.7500,
        'min_lng': 8.6000, 'max_lng': 8.9000,
        'flood_type': 'flash',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Hilly terrain with flash flooding in river valleys.',
    },
    {
        'zone_name': 'Wamba Mada River Flood Zone',
        'risk_level': 'medium',
        'state': 'Nasarawa',
        'lga': 'Wamba',
        'min_lat': 8.9500, 'max_lat': 9.1500,
        'min_lng': 8.5000, 'max_lng': 8.8000,
        'flood_type': 'riverine',
        'peak_months': 'August-October',
        'data_source': 'NIHSA AFO 2024 / Lower Benue RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Mada River catchment flooding in Wamba area.',
    },

    # ── BENUE STATE ───────────────────────────────────────────────────────────────
    {
        'zone_name': 'Kwande Katsina-Ala Flood Corridor',
        'risk_level': 'very_high',
        'state': 'Benue',
        'lga': 'Kwande',
        'min_lat': 6.8500, 'max_lat': 7.1500,
        'min_lng': 9.2500, 'max_lng': 9.6000,
        'flood_type': 'riverine',
        'peak_months': 'August-October',
        'data_source': 'NIHSA AFO 2024 / OCHA 2022',
        'last_major_flood_year': 2022,
        'notes': 'Katsina-Ala River — one of the most flood-prone LGAs in Benue State.',
    },
    {
        'zone_name': 'Guma Benue River Agricultural Plain',
        'risk_level': 'very_high',
        'state': 'Benue',
        'lga': 'Guma',
        'min_lat': 7.5000, 'max_lat': 7.7500,
        'min_lng': 8.1500, 'max_lng': 8.5000,
        'flood_type': 'riverine',
        'peak_months': 'August-October',
        'data_source': 'NIHSA AFO 2024 / Presidential Flood Committee 2022',
        'last_major_flood_year': 2022,
        'notes': 'Benue River plain — Guma is the food basket of Benue but suffers devastating annual floods.',
    },
    {
        'zone_name': 'Tarka Benue Tributary Zone',
        'risk_level': 'high',
        'state': 'Benue',
        'lga': 'Tarka',
        'min_lat': 7.2000, 'max_lat': 7.4500,
        'min_lng': 9.0000, 'max_lng': 9.3000,
        'flood_type': 'riverine',
        'peak_months': 'August-October',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Seasonal flooding of farming communities in Tarka LGA.',
    },

    # ── TARABA STATE ──────────────────────────────────────────────────────────────
    {
        'zone_name': 'Zing-Yorro Taraba River Corridor',
        'risk_level': 'high',
        'state': 'Taraba',
        'lga': 'Zing',
        'min_lat': 8.1500, 'max_lat': 8.5000,
        'min_lng': 11.7000, 'max_lng': 12.1000,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Taraba River upper course flooding.',
    },
    {
        'zone_name': 'Karim-Lamido Benue Tributary Zone',
        'risk_level': 'high',
        'state': 'Taraba',
        'lga': 'Karim-Lamido',
        'min_lat': 8.9000, 'max_lat': 9.2000,
        'min_lng': 11.4000, 'max_lng': 11.8000,
        'flood_type': 'riverine',
        'peak_months': 'August-October',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Remote community flooding on Benue tributaries in Taraba.',
    },

    # ── ADAMAWA STATE ─────────────────────────────────────────────────────────────
    {
        'zone_name': 'Ganye-Toungo Donga River Zone',
        'risk_level': 'high',
        'state': 'Adamawa',
        'lga': 'Ganye',
        'min_lat': 8.3500, 'max_lat': 8.6500,
        'min_lng': 12.0000, 'max_lng': 12.3500,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024 / Upper Benue RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Donga River flooding. Ganye is a major trade hub in southern Adamawa.',
    },
    {
        'zone_name': 'Michika-Madagali Mandara Mountain Flash Floods',
        'risk_level': 'medium',
        'state': 'Adamawa',
        'lga': 'Michika',
        'min_lat': 10.4000, 'max_lat': 10.8000,
        'min_lng': 13.3000, 'max_lng': 13.7000,
        'flood_type': 'flash',
        'peak_months': 'July-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Mandara Mountain foothills flash flooding. Area previously affected by insurgency.',
    },

    # ── GOMBE STATE ───────────────────────────────────────────────────────────────
    {
        'zone_name': 'Nafada-Dukku Gongola Flood Plain',
        'risk_level': 'high',
        'state': 'Gombe',
        'lga': 'Nafada',
        'min_lat': 10.8500, 'max_lat': 11.1500,
        'min_lng': 11.3000, 'max_lng': 11.7000,
        'flood_type': 'riverine',
        'peak_months': 'August-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Gongola River plain. Annual flooding displaces farming communities.',
    },

    # ── OGO STATE ─────────────────────────────────────────────────────────────────
    {
        'zone_name': 'Ijebu Ode-Sagamu Ogun Lagoon Fringe',
        'risk_level': 'medium',
        'state': 'Ogun',
        'lga': 'Ijebu Ode',
        'min_lat': 6.8000, 'max_lat': 6.9500,
        'min_lng': 3.9000, 'max_lng': 4.1000,
        'flood_type': 'combined',
        'peak_months': 'June-September',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Lagoon fringe and Ogun River tributary flooding in Ijebu area.',
    },
    {
        'zone_name': 'Owode-Egba Ogun River Basin',
        'risk_level': 'high',
        'state': 'Ogun',
        'lga': 'Obafemi-Owode',
        'min_lat': 6.8500, 'max_lat': 7.0000,
        'min_lng': 3.3500, 'max_lng': 3.5500,
        'flood_type': 'riverine',
        'peak_months': 'August-October',
        'data_source': 'NIHSA AFO 2024 / Ogun-Osun RBDA',
        'last_major_flood_year': 2022,
        'notes': 'Ogun River flooding downstream of Ikere Gorge Dam. Releases directly affect these communities.',
    },

    # ── IMO STATE ─────────────────────────────────────────────────────────────────
    {
        'zone_name': 'Ohaji-Egbema Niger River Fringe',
        'risk_level': 'very_high',
        'state': 'Imo',
        'lga': 'Ohaji/Egbema',
        'min_lat': 5.2500, 'max_lat': 5.5000,
        'min_lng': 6.7500, 'max_lng': 7.0000,
        'flood_type': 'riverine',
        'peak_months': 'August-November',
        'data_source': 'NIHSA AFO 2024 / NDDC',
        'last_major_flood_year': 2022,
        'notes': 'Niger River fringe approaching Niger Delta. Major oil-producing area with compound flood-contamination risk.',
    },

    # ── ANAMBRA STATE ─────────────────────────────────────────────────────────────
    {
        'zone_name': 'Anambra West Isoko Niger Flood Plain',
        'risk_level': 'critical',
        'state': 'Anambra',
        'lga': 'Anambra West',
        'min_lat': 6.2500, 'max_lat': 6.5000,
        'min_lng': 6.6000, 'max_lng': 6.8000,
        'flood_type': 'riverine',
        'peak_months': 'August-November',
        'data_source': 'NIHSA AFO 2024 / OCHA 2022',
        'last_major_flood_year': 2022,
        'notes': 'Anambra West is one of Nigeria\'s most flood-prone LGAs. Entire communities on islands accessible only by boat during flood season.',
    },
    {
        'zone_name': 'Ayamelum Niger River Flood Plain',
        'risk_level': 'critical',
        'state': 'Anambra',
        'lga': 'Ayamelum',
        'min_lat': 6.4500, 'max_lat': 6.7000,
        'min_lng': 6.8000, 'max_lng': 7.0000,
        'flood_type': 'riverine',
        'peak_months': 'August-November',
        'data_source': 'NIHSA AFO 2024 / OCHA 2022',
        'last_major_flood_year': 2022,
        'notes': 'Ayamelum LGA sits directly on Niger River plain. Annual critical flooding with communities completely isolated.',
    },

    # ── RIVERS STATE ──────────────────────────────────────────────────────────────
    {
        'zone_name': 'Andoni-Opobo Sea Level Watch Zone',
        'risk_level': 'critical',
        'state': 'Rivers',
        'lga': 'Andoni',
        'min_lat': 4.4000, 'max_lat': 4.6500,
        'min_lng': 7.4500, 'max_lng': 7.8000,
        'flood_type': 'coastal',
        'peak_months': 'June-November',
        'data_source': 'NIHSA AFO 2026 advance / NDDC / IPCC AR6',
        'last_major_flood_year': 2022,
        'notes': 'Low-lying Atlantic-facing Niger Delta communities. Sea-level rise watch zone. Communities at existential risk by 2050 under high-emission scenarios.',
    },
    {
        'zone_name': 'Omuma-Emohua Orashi River Zone',
        'risk_level': 'high',
        'state': 'Rivers',
        'lga': 'Omuma',
        'min_lat': 5.1500, 'max_lat': 5.4000,
        'min_lng': 6.8500, 'max_lng': 7.1500,
        'flood_type': 'riverine',
        'peak_months': 'August-November',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Orashi River plain flooding in central Rivers State.',
    },

    # ── DELTA STATE ───────────────────────────────────────────────────────────────
    {
        'zone_name': 'Bomadi-Patani Forcados River Zone',
        'risk_level': 'critical',
        'state': 'Delta',
        'lga': 'Bomadi',
        'min_lat': 5.2500, 'max_lat': 5.5000,
        'min_lng': 5.5000, 'max_lng': 5.9000,
        'flood_type': 'combined',
        'peak_months': 'August-November',
        'data_source': 'NIHSA AFO 2024 / NDDC',
        'last_major_flood_year': 2022,
        'notes': 'Forcados River distributary communities. Annual complete flooding of low-lying islands.',
    },
    {
        'zone_name': 'Burutu-Ughievwen Delta Fringe',
        'risk_level': 'very_high',
        'state': 'Delta',
        'lga': 'Burutu',
        'min_lat': 5.2000, 'max_lat': 5.4500,
        'min_lng': 5.5500, 'max_lng': 5.8500,
        'flood_type': 'coastal',
        'peak_months': 'July-November',
        'data_source': 'NIHSA AFO 2024 / NDDC',
        'last_major_flood_year': 2022,
        'notes': 'Deep Niger Delta coastal zone with tidal and riverine compound flooding.',
    },

    # ── CROSS RIVER STATE ─────────────────────────────────────────────────────────
    {
        'zone_name': 'Akpabuyo Calabar Estuary Coastal Zone',
        'risk_level': 'high',
        'state': 'Cross River',
        'lga': 'Akpabuyo',
        'min_lat': 4.8000, 'max_lat': 4.9500,
        'min_lng': 8.3000, 'max_lng': 8.5500,
        'flood_type': 'coastal',
        'peak_months': 'July-October',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Calabar estuary coastal communities. Tidal and storm surge flooding.',
    },

    # ── BAYELSA STATE ─────────────────────────────────────────────────────────────
    {
        'zone_name': 'Ekeremor-Southern Ijaw Atlantic Coast',
        'risk_level': 'critical',
        'state': 'Bayelsa',
        'lga': 'Ekeremor',
        'min_lat': 4.8000, 'max_lat': 5.0500,
        'min_lng': 5.7000, 'max_lng': 6.0000,
        'flood_type': 'coastal',
        'peak_months': 'July-November',
        'data_source': 'NIHSA AFO 2026 advance / NDDC / IPCC',
        'last_major_flood_year': 2022,
        'notes': 'Atlantic-facing Bayelsa communities below 1m elevation. Critical sea-level rise exposure. IPCC projects complete inundation risk by 2100 under high-emission scenarios.',
    },
    {
        'zone_name': 'Brass District Tidal Surge Zone',
        'risk_level': 'critical',
        'state': 'Bayelsa',
        'lga': 'Brass',
        'min_lat': 4.1500, 'max_lat': 4.3500,
        'min_lng': 5.9500, 'max_lng': 6.2500,
        'flood_type': 'coastal',
        'peak_months': 'June-November',
        'data_source': 'NIHSA AFO 2026 advance / NDDC',
        'last_major_flood_year': 2022,
        'notes': 'Brass LGA communities are at the Niger Delta Atlantic face. Multiple communities at elevation <0.5m. Highest sea-level rise risk in Nigeria.',
    },

    # ── AKWA IBOM ─────────────────────────────────────────────────────────────────
    {
        'zone_name': 'Oron-Mbo Coastal Flood Zone',
        'risk_level': 'very_high',
        'state': 'Akwa Ibom',
        'lga': 'Oron',
        'min_lat': 4.7500, 'max_lat': 4.9000,
        'min_lng': 8.2000, 'max_lng': 8.4500,
        'flood_type': 'coastal',
        'peak_months': 'July-October',
        'data_source': 'NIHSA AFO 2024 / NDDC',
        'last_major_flood_year': 2022,
        'notes': 'Oron coastal community — Atlantic tidal surge and Cross River estuary flooding.',
    },
    {
        'zone_name': 'Mkpat-Enin Qua Iboe River Zone',
        'risk_level': 'high',
        'state': 'Akwa Ibom',
        'lga': 'Mkpat-Enin',
        'min_lat': 4.7000, 'max_lat': 4.8500,
        'min_lng': 7.7500, 'max_lng': 8.0000,
        'flood_type': 'riverine',
        'peak_months': 'July-October',
        'data_source': 'NIHSA AFO 2024',
        'last_major_flood_year': 2022,
        'notes': 'Qua Iboe River flooding. Proximity to ExxonMobil terminal adds risk of contamination.',
    },
]


# ═══════════════════════════════════════════════════════════════════════════════
#  ADDITIONAL ACQUISITION AREAS — SECOND EXPANSION
# ═══════════════════════════════════════════════════════════════════════════════

ADDITIONAL_ACQUISITIONS2 = [

    # ── TARABA STATE ──────────────────────────────────────────────────────────────
    {
        'area_name': 'Kashimbila Dam Reservoir Acquisition Zone',
        'authority': 'Federal Ministry of Power / Taraba State Government',
        'acquisition_type': 'completed',
        'state': 'Taraba',
        'lga': 'Donga',
        'min_lat': 7.1500, 'max_lat': 7.4500,
        'min_lng': 9.6000, 'max_lng': 10.0000,
        'gazette_reference': 'Federal Ministry of Power Kashimbila EIA Gazette 2016',
        'data_source': 'TCN / Taraba State Government',
        'notes': 'Kashimbila Dam reservoir footprint — communities resettled. Private titles in this zone extinguished upon dam completion.',
    },
    {
        'area_name': 'Jalingo GRA Expansion',
        'authority': 'Taraba State Government',
        'acquisition_type': 'completed',
        'state': 'Taraba',
        'lga': 'Jalingo',
        'min_lat': 8.8900, 'max_lat': 8.9300,
        'min_lng': 11.3500, 'max_lng': 11.4000,
        'gazette_reference': 'Taraba State Gazette',
        'data_source': 'Taraba State Ministry of Lands',
        'notes': 'GRA expansion — allocation only through Taraba State Ministry of Lands.',
    },

    # ── PLATEAU STATE ─────────────────────────────────────────────────────────────
    {
        'area_name': 'Jos Tin Mining Reservation Areas',
        'authority': 'Mining Cadastre Office / Federal Ministry of Mines',
        'acquisition_type': 'completed',
        'state': 'Plateau',
        'lga': 'Barkin Ladi',
        'min_lat': 9.4500, 'max_lat': 9.6500,
        'min_lng': 8.8000, 'max_lng': 9.1500,
        'gazette_reference': 'Nigerian Minerals and Mining Act 2007',
        'data_source': 'Mining Cadastre Office / Plateau State',
        'notes': 'Active mining leases in Barkin Ladi and Jos South. Mining licences override private land titles in these areas.',
    },
    {
        'area_name': 'Jos North Airport Buffer and Military Area',
        'authority': 'FAAN / Nigerian Air Force',
        'acquisition_type': 'completed',
        'state': 'Plateau',
        'lga': 'Jos North',
        'min_lat': 9.8600, 'max_lat': 9.9000,
        'min_lng': 8.8500, 'max_lng': 8.9200,
        'gazette_reference': 'FAAN Aerodrome Safety Notice / NAF Base Gazette',
        'data_source': 'FAAN / Nigerian Air Force',
        'notes': 'Yakubu Gowon Airport safety buffer and adjacent Air Force base buffer zone.',
    },

    # ── NIGER STATE ───────────────────────────────────────────────────────────────
    {
        'area_name': 'Minna Airport Buffer Zone',
        'authority': 'FAAN / Niger State Government',
        'acquisition_type': 'completed',
        'state': 'Niger',
        'lga': 'Bosso',
        'min_lat': 9.6300, 'max_lat': 9.6700,
        'min_lng': 6.4600, 'max_lng': 6.5200,
        'gazette_reference': 'FAAN Aerodrome Safety Notice',
        'data_source': 'FAAN',
        'notes': 'Minna Airport safety buffer — no building above 6m height.',
    },
    {
        'area_name': 'Shiroro Dam Safety Zone',
        'authority': 'Shiroro Hydro Electric Power Plc / Federal Government',
        'acquisition_type': 'completed',
        'state': 'Niger',
        'lga': 'Shiroro',
        'min_lat': 9.9000, 'max_lat': 10.1000,
        'min_lng': 6.7000, 'max_lng': 7.0000,
        'gazette_reference': 'NEPA/PHCN Dam Safety Zone Notice',
        'data_source': 'Shiroro Hydro / TCN',
        'notes': 'Dam safety exclusion zone. Private development prohibited within this radius of Shiroro Dam.',
    },
    {
        'area_name': 'Kainji Dam and Reservoir Buffer Zone',
        'authority': 'Nigerian Electricity Supply Corporation / Kainji Hydro Electric Plc',
        'acquisition_type': 'completed',
        'state': 'Niger',
        'lga': 'Borgu',
        'min_lat': 10.2000, 'max_lat': 10.8000,
        'min_lng': 4.3000, 'max_lng': 4.8500,
        'gazette_reference': 'NEPA Dam Reservation Gazette 1968',
        'data_source': 'Kainji Hydro Electric Plc / NBET',
        'notes': 'Kainji Lake reservoir safety zone. All land within the historic reservoir footprint was compulsorily acquired. Adjacent areas subject to dam safety buffer restrictions.',
    },
    {
        'area_name': 'Zungeru Dam Safety and Operations Zone',
        'authority': 'China Gezhouba Group / TCN / Federal Government',
        'acquisition_type': 'completed',
        'state': 'Niger',
        'lga': 'Shiroro',
        'min_lat': 9.7000, 'max_lat': 9.9500,
        'min_lng': 6.0500, 'max_lng': 6.3000,
        'gazette_reference': 'FGN Zungeru Dam Gazette 2016',
        'data_source': 'Federal Ministry of Power / TCN',
        'notes': 'Zungeru Hydroelectric Dam (700MW) safety exclusion zone and operations area. Large reservoir footprint in Shiroro LGA with compulsory acquisition of communities.',
    },

    # ── KWARA STATE ───────────────────────────────────────────────────────────────
    {
        'area_name': 'Ilorin Airport Safety Buffer',
        'authority': 'FAAN / Kwara State Government',
        'acquisition_type': 'completed',
        'state': 'Kwara',
        'lga': 'Ilorin West',
        'min_lat': 8.4700, 'max_lat': 8.5200,
        'min_lng': 4.4700, 'max_lng': 4.5300,
        'gazette_reference': 'FAAN Aerodrome Safety Notice',
        'data_source': 'FAAN',
        'notes': 'Ilorin Airport safety buffer and approach path restrictions.',
    },

    # ── BORNO STATE ───────────────────────────────────────────────────────────────
    {
        'area_name': 'Maiduguri-Dikwa Federal Road Reconstruction ROW',
        'authority': 'Federal Ministry of Works / RMRP',
        'acquisition_type': 'ongoing',
        'state': 'Borno',
        'lga': 'Jere',
        'min_lat': 11.8000, 'max_lat': 11.9000,
        'min_lng': 13.2500, 'max_lng': 13.6000,
        'gazette_reference': 'Federal Highway ROW Notice',
        'data_source': 'Federal Ministry of Works',
        'notes': 'Federal road reconstruction ROW for Maiduguri-Dikwa highway rehabilitation.',
    },

    # ── KOGI STATE ────────────────────────────────────────────────────────────────
    {
        'area_name': 'Lokoja-Abuja Federal Road Corridor (Kogi segment)',
        'authority': 'Federal Ministry of Works',
        'acquisition_type': 'ongoing',
        'state': 'Kogi',
        'lga': 'Kogi',
        'min_lat': 7.7000, 'max_lat': 8.0000,
        'min_lng': 6.6500, 'max_lng': 6.9000,
        'gazette_reference': 'Federal Highway ROW Notice',
        'data_source': 'Federal Ministry of Works',
        'notes': 'Federal road expansion ROW. Land fronting the Lokoja-Abuja highway subject to setback and widening controls.',
    },

    # ── NASARAWA STATE ────────────────────────────────────────────────────────────
    {
        'area_name': 'Nasarawa State University Keffi Land Reservation',
        'authority': 'Nasarawa State Government',
        'acquisition_type': 'completed',
        'state': 'Nasarawa',
        'lga': 'Keffi',
        'min_lat': 8.8400, 'max_lat': 8.8800,
        'min_lng': 7.8700, 'max_lng': 7.9100,
        'gazette_reference': 'Nasarawa State Gazette (University Campus)',
        'data_source': 'Nasarawa State Ministry of Lands',
        'notes': 'University campus reservation — surrounding land subject to state planning control.',
    },

    # ── EDO STATE ─────────────────────────────────────────────────────────────────
    {
        'area_name': 'Benin-Lagos Federal Road ROW (Edo segment)',
        'authority': 'Federal Ministry of Works',
        'acquisition_type': 'ongoing',
        'state': 'Edo',
        'lga': 'Orhionmwon',
        'min_lat': 6.1000, 'max_lat': 6.4000,
        'min_lng': 5.4500, 'max_lng': 5.6500,
        'gazette_reference': 'Federal Highway ROW Notice',
        'data_source': 'Federal Ministry of Works',
        'notes': 'Benin City-Lagos federal highway ROW. Land fronting the corridor subject to setback restrictions.',
    },
    {
        'area_name': 'Edo Museum of West African Art (EMOWAA) Buffer',
        'authority': 'Edo State Government / Federal Government',
        'acquisition_type': 'ongoing',
        'state': 'Edo',
        'lga': 'Oredo',
        'min_lat': 6.3300, 'max_lat': 6.3600,
        'min_lng': 5.6100, 'max_lng': 5.6500,
        'gazette_reference': 'Edo State Gazette 2022',
        'data_source': 'Edo State Ministry of Lands',
        'notes': 'New EMOWAA cultural zone in Benin City centre. Adjacent properties subject to heritage zone restrictions.',
    },

    # ── ANAMBRA STATE ─────────────────────────────────────────────────────────────
    {
        'area_name': 'Onitsha-Nnewi Expressway ROW',
        'authority': 'Anambra State Government / Federal Ministry of Works',
        'acquisition_type': 'ongoing',
        'state': 'Anambra',
        'lga': 'Ogbaru',
        'min_lat': 6.0000, 'max_lat': 6.1500,
        'min_lng': 6.7500, 'max_lng': 6.9000,
        'gazette_reference': 'Anambra State Gazette / Federal Highway Notice',
        'data_source': 'Anambra State Ministry of Works',
        'notes': 'Major expressway corridor under active development. Frontage properties subject to acquisition and setback controls.',
    },

    # ── ENUGU STATE ───────────────────────────────────────────────────────────────
    {
        'area_name': 'Enugu-Port Harcourt Expressway ROW (Enugu segment)',
        'authority': 'Federal Ministry of Works',
        'acquisition_type': 'ongoing',
        'state': 'Enugu',
        'lga': 'Oji-River',
        'min_lat': 6.3000, 'max_lat': 6.5500,
        'min_lng': 7.2500, 'max_lng': 7.5000,
        'gazette_reference': 'Federal Highway ROW Notice',
        'data_source': 'Federal Ministry of Works',
        'notes': 'Enugu-Port Harcourt Expressway federal corridor. Active widening and setback enforcement.',
    },
    {
        'area_name': 'Enugu Airport Safety Buffer',
        'authority': 'FAAN',
        'acquisition_type': 'completed',
        'state': 'Enugu',
        'lga': 'Enugu East',
        'min_lat': 6.4550, 'max_lat': 6.4900,
        'min_lng': 7.5400, 'max_lng': 7.5900,
        'gazette_reference': 'FAAN Aerodrome Safety Notice',
        'data_source': 'FAAN',
        'notes': 'Akanu Ibiam International Airport safety buffer zone.',
    },

    # ── OSUN STATE ────────────────────────────────────────────────────────────────
    {
        'area_name': 'Osun-Osogbo Sacred Grove UNESCO Buffer',
        'authority': 'Osun State Government / UNESCO',
        'acquisition_type': 'completed',
        'state': 'Osun',
        'lga': 'Osogbo',
        'min_lat': 7.7500, 'max_lat': 7.7800,
        'min_lng': 4.5500, 'max_lng': 4.5900,
        'gazette_reference': 'Osun State Heritage Gazette / UNESCO World Heritage Site',
        'data_source': 'Osun State Ministry of Culture / UNESCO',
        'notes': 'UNESCO World Heritage Site — no private development allowed within defined buffer. Adjacent properties subject to heritage zone restrictions.',
    },

    # ── RIVERS STATE ──────────────────────────────────────────────────────────────
    {
        'area_name': 'Eleme Petrochemical Complex Buffer',
        'authority': 'Nigerian National Petroleum Corporation / INDORAMA',
        'acquisition_type': 'completed',
        'state': 'Rivers',
        'lga': 'Eleme',
        'min_lat': 4.7800, 'max_lat': 4.8500,
        'min_lng': 7.1500, 'max_lng': 7.2500,
        'gazette_reference': 'Petroleum Act / Federal Government Gazette',
        'data_source': 'NNPC / NUPRC',
        'notes': 'Port Harcourt Refinery and Petrochemical Company buffer zone. Industrial buffer restricts private development.',
    },
    {
        'area_name': 'Finima LNG Bonny Island Buffer',
        'authority': 'NLNG / NNPC / Federal Government',
        'acquisition_type': 'completed',
        'state': 'Rivers',
        'lga': 'Bonny',
        'min_lat': 4.4200, 'max_lat': 4.5000,
        'min_lng': 7.1200, 'max_lng': 7.2000,
        'gazette_reference': 'NLNG Bonny Island Acquisition Gazette',
        'data_source': 'NLNG / NNPC',
        'notes': 'NLNG Finima terminal on Bonny Island. Extensive buffer zone with no private acquisition.',
    },

    # ── BAYELSA STATE ─────────────────────────────────────────────────────────────
    {
        'area_name': 'Yenagoa-Mbiama Federal Road ROW',
        'authority': 'Federal Ministry of Works',
        'acquisition_type': 'ongoing',
        'state': 'Bayelsa',
        'lga': 'Yenagoa',
        'min_lat': 4.9000, 'max_lat': 5.0500,
        'min_lng': 6.1500, 'max_lng': 6.3500,
        'gazette_reference': 'Federal Highway ROW Notice',
        'data_source': 'Federal Ministry of Works',
        'notes': 'Yenagoa-Mbiama trunk road expansion ROW in flood-prone zone.',
    },
    {
        'area_name': 'Agip/Eni Nigeria Pipeline Corridor (Bayelsa)',
        'authority': 'Agip/Eni Nigeria / NNPC / Federal Government',
        'acquisition_type': 'completed',
        'state': 'Bayelsa',
        'lga': 'Ogbia',
        'min_lat': 4.6000, 'max_lat': 4.9000,
        'min_lng': 6.3500, 'max_lng': 6.6500,
        'gazette_reference': 'Petroleum Pipeline ROW Notice / OML Licence',
        'data_source': 'NNPC / NUPRC',
        'notes': 'Agip/Eni oil and gas pipeline network in Ogbia LGA — birthplace of Ken Saro-Wiwa area. Extensive ROW restrictions.',
    },

    # ── DELTA STATE ───────────────────────────────────────────────────────────────
    {
        'area_name': 'Ughelli-Sapele SPDC Pipeline Corridor',
        'authority': 'Shell Petroleum Development Company / NNPC',
        'acquisition_type': 'completed',
        'state': 'Delta',
        'lga': 'Ughelli North',
        'min_lat': 5.4500, 'max_lat': 5.6500,
        'min_lng': 5.9500, 'max_lng': 6.2000,
        'gazette_reference': 'Petroleum Pipeline ROW Notice',
        'data_source': 'NNPC / NUPRC',
        'notes': 'Major SPDC pipeline corridor in Delta State. Extensive setback requirements. Pipeline proximity increases contamination risk during floods.',
    },
]