"""
Management command: python manage.py seed_data

The most comprehensive Nigerian land risk dataset available in open source.
Sourced from:
  - NIHSA Annual Flood Outlooks 2021, 2022, 2023, 2024
  - NEMA flood situation reports
  - OCHA Nigeria flood reports 2022, 2023, 2024
  - Wikipedia: List of dams and reservoirs in Nigeria
  - UNDP Nigeria Flood Impact Assessment 2022-2023
  - Lagos State Ministry of Lands / LASURA
  - FCDA / AGIS Abuja land records
  - Published geospatial research (ResearchGate, academic papers)
  - 2022 Nigeria floods Wikipedia article
  - YELF Climate Trust Foundation flood impact analysis 2025
"""
from django.core.management.base import BaseCommand
from apps.scans.models import FloodRiskZone, AcquisitionArea, Dam

FLOOD_ZONES = [
    {'zone_name':'Lekki-Victoria Island Coastal Flood Zone','risk_level':'very_high','state':'Lagos','lga':'Eti-Osa','min_lat':6.4200,'max_lat':6.5500,'min_lng':3.3800,'max_lng':3.7200,'flood_type':'coastal','peak_months':'June-October','data_source':'NIHSA AFO 2023 / Lagos State Ministry of Environment','last_major_flood_year':2022,'notes':'Low-lying coastal barrier island with average elevation of 2-4m. Highly susceptible to tidal surge, coastal flooding, and sea-level rise. Experienced severe flooding in 2012 (worst in 50 years). IPCC projects 3-4mm/year sea level rise in Gulf of Guinea. Entire Lekki Peninsula is at existential risk by 2050 under high-emission scenarios.'},
    {'zone_name':'Badagry Creek Coastal Zone','risk_level':'very_high','state':'Lagos','lga':'Badagry','min_lat':6.2500,'max_lat':6.4300,'min_lng':2.8500,'max_lng':3.1800,'flood_type':'coastal','peak_months':'July-October','data_source':'NIHSA AFO 2023 / NEMA','last_major_flood_year':2022,'notes':'Tidal creek system along Atlantic coast. Severe storm surge and tidal flooding. Communities built on reclaimed mangrove swamps.'},
    {'zone_name':'Apapa-Ijora Lagos Lagoon Fringe','risk_level':'high','state':'Lagos','lga':'Apapa','min_lat':6.4200,'max_lat':6.4750,'min_lng':3.3400,'max_lng':3.4000,'flood_type':'urban','peak_months':'June-September','data_source':'LASEMA','last_major_flood_year':2023,'notes':'Industrial zone on Lagos Lagoon fringe. Perennial drainage failure. Proximity to lagoon causes backflow flooding.'},
    {'zone_name':'Ikorodu Lagoon Communities','risk_level':'high','state':'Lagos','lga':'Ikorodu','min_lat':6.5500,'max_lat':6.6800,'min_lng':3.4800,'max_lng':3.7000,'flood_type':'combined','peak_months':'July-October','data_source':'NIHSA AFO 2023 / NEMA 2022','last_major_flood_year':2022,'notes':'Lagoon-edge communities in northern Lagos. Seasonal flooding from Lagos Lagoon overflow.'},
    {'zone_name':'Surulere-Mushin Flash Flood Zone','risk_level':'medium','state':'Lagos','lga':'Surulere','min_lat':6.4850,'max_lat':6.5250,'min_lng':3.3300,'max_lng':3.3900,'flood_type':'urban','peak_months':'May-September','data_source':'Lagos State Ministry of Environment 2020','last_major_flood_year':2023,'notes':'Dense urban area with severely inadequate drainage infrastructure.'},
    {'zone_name':'Sangotedo-Ajah Flood Corridor','risk_level':'medium','state':'Lagos','lga':'Eti-Osa','min_lat':6.4550,'max_lat':6.4950,'min_lng':3.5500,'max_lng':3.6500,'flood_type':'flash','peak_months':'June-September','data_source':'NIHSA 2023 / ResearchGate geospatial study','last_major_flood_year':2023,'notes':'Rapidly developing peri-urban area without adequate stormwater drainage planning.'},
    {'zone_name':'Ibeju-Lekki Deep Waterfront Zone','risk_level':'high','state':'Lagos','lga':'Ibeju-Lekki','min_lat':6.3500,'max_lat':6.4700,'min_lng':3.7200,'max_lng':4.0500,'flood_type':'coastal','peak_months':'July-October','data_source':'NIHSA / Lagos State Ministry of Physical Planning','last_major_flood_year':2022,'notes':'Rapidly developing Atlantic-facing zone. Large tracts are reclaimed wetland. Government acquisition zones overlap heavily with this area.'},
    {'zone_name':'Port Harcourt Waterfront Communities','risk_level':'very_high','state':'Rivers','lga':'Port Harcourt','min_lat':4.7600,'max_lat':4.9000,'min_lng':6.9600,'max_lng':7.1000,'flood_type':'coastal','peak_months':'July-November','data_source':'NIHSA / NDDC 2022 / OCHA Nigeria 2022','last_major_flood_year':2022,'notes':'Tidal and storm surge flooding on mangrove-reclaimed land. 5 LGAs severely inundated in 2022. 150,000+ people displaced in Ahoada West LGA alone.'},
    {'zone_name':'Ahoada West-Ogba-Egbema Flood Plain','risk_level':'very_high','state':'Rivers','lga':'Ahoada West','min_lat':5.0500,'max_lat':5.3000,'min_lng':6.5500,'max_lng':6.8500,'flood_type':'riverine','peak_months':'August-November','data_source':'OCHA Nigeria Situation Report October 2022','last_major_flood_year':2022,'notes':'150,000 people displaced and inaccessible during 2022 floods. River Niger flood plain.'},
    {'zone_name':'Yenagoa Tidal Flood Zone','risk_level':'critical','state':'Bayelsa','lga':'Yenagoa','min_lat':4.8900,'max_lat':5.0200,'min_lng':6.2000,'max_lng':6.3800,'flood_type':'combined','peak_months':'August-November','data_source':'NIHSA / OCHA Nigeria 2022 / YELF Climate Trust 2025','last_major_flood_year':2022,'notes':'State capital sits below sea level in parts. Worst-affected state in 2022 floods. 700,000+ people displaced or affected. 1.3 million people victims across Bayelsa in 2022.'},
    {'zone_name':'Ogbia-Nembe Niger Delta Flood Plain','risk_level':'critical','state':'Bayelsa','lga':'Ogbia','min_lat':4.6500,'max_lat':4.8900,'min_lng':6.0500,'max_lng':6.4500,'flood_type':'combined','peak_months':'July-November','data_source':'NIHSA AFO 2023 / NEMA','last_major_flood_year':2022,'notes':'Deep Niger Delta. River Niger overflow combined with tidal surge. Communities completely isolated for months.'},
    {'zone_name':'Asaba-Aniocha Niger River Flood Plain','risk_level':'very_high','state':'Delta','lga':'Aniocha South','min_lat':6.1000,'max_lat':6.2500,'min_lng':6.6000,'max_lng':6.8500,'flood_type':'riverine','peak_months':'September-November','data_source':'NIHSA AFO 2023 / UNDP Flood Assessment 2022','last_major_flood_year':2022,'notes':'River Niger overflow annually inundates riverside communities. Part of NIHSA priority states in 2024 AFO.'},
    {'zone_name':'Warri-Uvwie Industrial Flood Zone','risk_level':'high','state':'Delta','lga':'Uvwie','min_lat':5.4800,'max_lat':5.5800,'min_lng':5.6500,'max_lng':5.8000,'flood_type':'urban','peak_months':'June-October','data_source':'NIHSA / NEMA 2022','last_major_flood_year':2022,'notes':'Major oil industry hub. Flooding disrupts oil production and export.'},
    {'zone_name':'Onitsha-Anambra West Niger Flood Plain','risk_level':'critical','state':'Anambra','lga':'Onitsha North','min_lat':6.0800,'max_lat':6.2200,'min_lng':6.6800,'max_lng':6.8500,'flood_type':'riverine','peak_months':'August-November','data_source':'NIHSA AFO 2023 / Wikipedia 2022 Nigeria Floods','last_major_flood_year':2022,'notes':'Epicentre of 2022 Nigerian flood crisis. Over 200,000 people affected. Okpoko LGA single largest displacement hotspot. 76 people drowned when boat capsized Oct 7, 2022.'},
    {'zone_name':'Ogbaru-Atani Niger River Fringe','risk_level':'very_high','state':'Anambra','lga':'Ogbaru','min_lat':5.8500,'max_lat':6.0800,'min_lng':6.6000,'max_lng':6.8000,'flood_type':'riverine','peak_months':'September-November','data_source':'OCHA 2022 / NIHSA AFO 2023','last_major_flood_year':2022,'notes':'IDP camp at Atani was itself submerged during 2022 floods. Communities only accessible by canoe during peak flood season.'},
    {'zone_name':'Makurdi Benue River Basin','risk_level':'very_high','state':'Benue','lga':'Makurdi','min_lat':7.6000,'max_lat':7.8000,'min_lng':8.4500,'max_lng':8.7000,'flood_type':'riverine','peak_months':'August-October','data_source':'NIHSA AFO 2023 / NEMA / OCHA Nigeria 2023','last_major_flood_year':2023,'notes':'Benue River peaks at Makurdi annually. Exacerbated by Lagdo Dam releases from Cameroon. NEMA activated emergency response October 2023.'},
    {'zone_name':'Lokoja River Niger-Benue Confluence Zone','risk_level':'critical','state':'Kogi','lga':'Lokoja','min_lat':7.7000,'max_lat':7.9000,'min_lng':6.6500,'max_lng':6.9000,'flood_type':'riverine','peak_months':'September-November','data_source':'OCHA Nigeria Situation Report 2024 / NIHSA','last_major_flood_year':2024,'notes':'Located at the exact confluence of River Niger and River Benue. When both rivers peak simultaneously, catastrophic flooding occurs. 113.3km of roads submerged in Oct 2022. Named by NIHSA as priority zone in every Annual Flood Outlook since 2018.'},
    {'zone_name':'Ibaji-Kogi LGA Niger Flood Plain','risk_level':'very_high','state':'Kogi','lga':'Ibaji','min_lat':7.2000,'max_lat':7.5000,'min_lng':6.7000,'max_lng':7.0000,'flood_type':'riverine','peak_months':'August-November','data_source':'NIHSA AFO 2022 / UNDP Nigeria Flood Assessment 2022-2023','last_major_flood_year':2022,'notes':'Part of UNDP priority assessment states for 2022 flood. Communities relocated annually.'},
    {'zone_name':'Yola-Jimeta Benue River Zone','risk_level':'very_high','state':'Adamawa','lga':'Yola South','min_lat':9.1000,'max_lat':9.3000,'min_lng':12.3500,'max_lng':12.6000,'flood_type':'riverine','peak_months':'August-October','data_source':'YELF Climate Trust 2025 / NEMA Oct 2023','last_major_flood_year':2023,'notes':'14 out of 21 Adamawa LGAs severely flooded Oct 2023. 51,043 individuals displaced. Lagdo Dam releases cascade directly through this region.'},
    {'zone_name':'Mariga-Rijau Niger River Flood Zone','risk_level':'very_high','state':'Niger','lga':'Rijau','min_lat':11.0000,'max_lat':11.3000,'min_lng':5.0000,'max_lng':5.4000,'flood_type':'riverine','peak_months':'August-October','data_source':'Wikipedia 2022 Nigeria Floods','last_major_flood_year':2022,'notes':'Over 1,500 corpses washed away from Mariga cemetery in 2022 floods.'},
    {'zone_name':'Kainji Lake Downstream Communities','risk_level':'high','state':'Niger','lga':'Borgu','min_lat':9.8000,'max_lat':10.6000,'min_lng':4.3000,'max_lng':4.9000,'flood_type':'riverine','peak_months':'September-October','data_source':'NIHSA / Britannica Niger Dams Project','last_major_flood_year':2022,'notes':'Communities downstream of Kainji, Jebba, and Shiroro dams.'},
    {'zone_name':'Benin City Urban Flash Flood Zone','risk_level':'high','state':'Edo','lga':'Oredo','min_lat':6.2900,'max_lat':6.4200,'min_lng':5.5800,'max_lng':5.7000,'flood_type':'urban','peak_months':'June-September','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Benin City listed by NIHSA 2023 as urban flash flood risk city.'},
    {'zone_name':'Etsako-Owan River Niger Tributary Zone','risk_level':'high','state':'Edo','lga':'Etsako West','min_lat':7.0000,'max_lat':7.3500,'min_lng':6.0000,'max_lng':6.4000,'flood_type':'riverine','peak_months':'September-November','data_source':'NIHSA AFO 2024 / OCHA 2024','last_major_flood_year':2024,'notes':'NIHSA 2024 recommends Edo as priority state for humanitarian action. Downstream of Niger-Benue confluence at Lokoja.'},
    {'zone_name':'Calabar Coastal Flood Zone','risk_level':'high','state':'Cross River','lga':'Calabar Municipal','min_lat':4.8500,'max_lat':5.0200,'min_lng':8.2500,'max_lng':8.4000,'flood_type':'coastal','peak_months':'July-October','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Calabar listed by NIHSA 2023 as flash/urban flood risk city. Cross River listed as NIHSA priority state 2022, 2023, 2024.'},
    {'zone_name':'Eket-Ibeno Atlantic Coastal Zone','risk_level':'very_high','state':'Akwa Ibom','lga':'Ibeno','min_lat':4.5200,'max_lat':4.7500,'min_lng':7.8500,'max_lng':8.1000,'flood_type':'coastal','peak_months':'July-October','data_source':'NIHSA AFO 2023 / NEMA','last_major_flood_year':2022,'notes':'Low-lying coastal Atlantic zone. ExxonMobil Qua Iboe Terminal nearby. Akwa Ibom listed as high flood risk state in NIHSA 2022, 2023, 2024.'},
    {'zone_name':'Owerri Urban Flood Zone','risk_level':'high','state':'Imo','lga':'Owerri Municipal','min_lat':5.4500,'max_lat':5.5800,'min_lng':7.0000,'max_lng':7.1500,'flood_type':'urban','peak_months':'June-September','data_source':'NIHSA AFO 2023','last_major_flood_year':2023,'notes':'Owerri listed by NIHSA 2023 as urban flash flood risk city. Imo listed as high risk state in every NIHSA AFO 2021-2024.'},
    {'zone_name':'Aba Urban Flash Flood Zone','risk_level':'high','state':'Abia','lga':'Aba North','min_lat':5.0800,'max_lat':5.2000,'min_lng':7.3000,'max_lng':7.4500,'flood_type':'urban','peak_months':'June-September','data_source':'NIHSA AFO 2023 / NEMA','last_major_flood_year':2022,'notes':'Aba is a major commercial hub with severely blocked drainage channels. Recurrent flash flooding paralysing markets.'},
    {'zone_name':'Abakaliki-Ebonyi River Basin','risk_level':'high','state':'Ebonyi','lga':'Abakaliki','min_lat':6.2500,'max_lat':6.4500,'min_lng':8.0500,'max_lng':8.2500,'flood_type':'riverine','peak_months':'July-October','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Abakaliki listed by NIHSA 2023 as urban flash flood risk. Flooding compounded by lead and zinc mining runoff.'},
    {'zone_name':'Ogun-Yewa River Basin Flood Plain','risk_level':'very_high','state':'Ogun','lga':'Abeokuta North','min_lat':7.1000,'max_lat':7.3500,'min_lng':3.2000,'max_lng':3.4500,'flood_type':'riverine','peak_months':'July-October','data_source':'NIHSA AFO 2023 / ResearchGate HEC-GeoHMS study','last_major_flood_year':2022,'notes':'Ogun River basin. Downstream of Oyan Dam — dam releases compound natural flooding.'},
    {'zone_name':'Ondo-Ilaje Atlantic Coastal Zone','risk_level':'high','state':'Ondo','lga':'Ilaje','min_lat':6.0000,'max_lat':6.2500,'min_lng':4.8500,'max_lng':5.3000,'flood_type':'coastal','peak_months':'June-October','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'NIHSA 2023 lists Ondo for coastal flooding due to sea level rise and tidal surge.'},
    {'zone_name':'Ibadan Ogunpa River Flash Flood Zone','risk_level':'high','state':'Oyo','lga':'Ibadan North','min_lat':7.3200,'max_lat':7.4800,'min_lng':3.8500,'max_lng':4.0500,'flood_type':'urban','peak_months':'June-September','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Ibadan listed by NIHSA 2023 for urban flash flooding. Ogunpa River floods have killed hundreds historically. 2011 Ogunpa flood killed 100+ people.'},
    {'zone_name':'Jebba-Edu River Niger Flood Zone','risk_level':'very_high','state':'Kwara','lga':'Edu','min_lat':8.9000,'max_lat':9.2000,'min_lng':4.7000,'max_lng':5.1000,'flood_type':'riverine','peak_months':'September-October','data_source':'NIHSA / NEMA','last_major_flood_year':2022,'notes':'Downstream of Jebba Dam. When Kainji and Jebba simultaneously release water, communities face compound flooding.'},
    {'zone_name':'Lafia Benue Tributary Zone','risk_level':'high','state':'Nasarawa','lga':'Lafia','min_lat':8.4000,'max_lat':8.6000,'min_lng':8.4500,'max_lng':8.7000,'flood_type':'combined','peak_months':'August-October','data_source':'NIHSA AFO 2023','last_major_flood_year':2023,'notes':'Lafia listed by NIHSA for urban flooding. Nasarawa listed in NIHSA priority states.'},
    {'zone_name':'Hadejia River Wetlands Flood Zone','risk_level':'very_high','state':'Jigawa','lga':'Hadejia','min_lat':12.3000,'max_lat':12.7000,'min_lng':9.8000,'max_lng':10.3000,'flood_type':'riverine','peak_months':'August-September','data_source':'NIHSA AFO 2022 / Wikipedia 2022 Nigeria Floods','last_major_flood_year':2022,'notes':'At least 92 people died in Jigawa State flooding Aug-Sep 2022. Hadejia-Nguru wetlands.'},
    {'zone_name':'Birnin Kebbi-Argungu River Niger Zone','risk_level':'high','state':'Kebbi','lga':'Birnin Kebbi','min_lat':12.3500,'max_lat':12.6000,'min_lng':4.0000,'max_lng':4.3000,'flood_type':'riverine','peak_months':'August-September','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Birnin Kebbi listed by NIHSA 2023 for urban flooding. Downstream of Kainji Dam on River Niger.'},
    {'zone_name':'Sokoto River Basin Flood Zone','risk_level':'high','state':'Sokoto','lga':'Sokoto North','min_lat':12.9000,'max_lat':13.2000,'min_lng':5.1500,'max_lng':5.4500,'flood_type':'riverine','peak_months':'July-September','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Sokoto city listed by NIHSA 2023 for urban flooding. Downstream of Goronyo Dam.'},
    {'zone_name':'Kano Urban Flash Flood Zone','risk_level':'high','state':'Kano','lga':'Kano Municipal','min_lat':11.9500,'max_lat':12.1200,'min_lng':8.4500,'max_lng':8.6000,'flood_type':'urban','peak_months':'July-September','data_source':'NIHSA AFO 2023','last_major_flood_year':2023,'notes':'Kano listed by NIHSA 2023 for urban flash flooding. Kano State listed in NIHSA high-risk states 2022, 2023, 2024.'},
    {'zone_name':'Kaduna River Urban Flood Zone','risk_level':'high','state':'Kaduna','lga':'Kaduna North','min_lat':10.4800,'max_lat':10.6500,'min_lng':7.4000,'max_lng':7.5500,'flood_type':'urban','peak_months':'July-September','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Kaduna River runs through the city. Kaduna city listed by NIHSA 2023 for urban flood risk.'},
    {'zone_name':'Gombe-Dadin Kowa River Zone','risk_level':'high','state':'Gombe','lga':'Gombe','min_lat':10.2000,'max_lat':10.4000,'min_lng':11.0500,'max_lng':11.3000,'flood_type':'riverine','peak_months':'August-October','data_source':'NIHSA AFO 2023','last_major_flood_year':2022,'notes':'Gombe city listed for urban flood risk by NIHSA 2023. Downstream of Dadin Kowa Dam on Gongola River.'},
    {'zone_name':'Jalingo Taraba River Basin','risk_level':'very_high','state':'Taraba','lga':'Jalingo','min_lat':8.7500,'max_lat':9.0000,'min_lng':11.2000,'max_lng':11.5000,'flood_type':'riverine','peak_months':'August-October','data_source':'NIHSA AFO 2022 / NEMA Oct 2023','last_major_flood_year':2023,'notes':'NEMA activated emergency response Oct 2023 specifically for Taraba. Taraba River and Benue River tributaries overflow annually.'},
    {'zone_name':'Yobe Komadugu River Zone','risk_level':'medium','state':'Yobe','lga':'Nguru','min_lat':12.8000,'max_lat':13.0500,'min_lng':10.5000,'max_lng':10.9000,'flood_type':'riverine','peak_months':'July-September','data_source':'Wikipedia 2022 Nigeria Floods / NIHSA','last_major_flood_year':2022,'notes':'Severe flooding struck Yobe State July 2022 killing 4 people.'},
    {'zone_name':'Gwagwalada River Niger Tributary Plain','risk_level':'high','state':'FCT','lga':'Gwagwalada','min_lat':8.9000,'max_lat':9.0200,'min_lng':7.0400,'max_lng':7.2000,'flood_type':'riverine','peak_months':'August-October','data_source':'NEMA Flood Risk Map 2022 / NIHSA','last_major_flood_year':2022,'notes':'River plain subject to annual flooding from Gurara River system.'},
    {'zone_name':'Kuje-Kwali Seasonal Watercourse Zone','risk_level':'medium','state':'FCT','lga':'Kuje','min_lat':8.8500,'max_lat':8.9600,'min_lng':7.2000,'max_lng':7.3200,'flood_type':'flash','peak_months':'August-September','data_source':'NIHSA 2021 / AGIS FCT','last_major_flood_year':2022,'notes':'Seasonal flash flooding August-September.'},
    {'zone_name':'Abuja City Centre Flash Flood Risk','risk_level':'low','state':'FCT','lga':'Abuja Municipal','min_lat':9.0200,'max_lat':9.0900,'min_lng':7.4500,'max_lng':7.5400,'flood_type':'urban','peak_months':'July-September','data_source':'AGIS / FCT Development Control','last_major_flood_year':2022,'notes':'Well-planned core city centre with adequate drainage infrastructure. Low flood risk.'},
]

DAMS = [
    {'name':'Kainji Dam','river_basin':'Niger','state':'Niger','country':'Nigeria','latitude':10.3967,'longitude':4.5833,'capacity_mcm':15000,'height_m':66,'year_completed':1969,'purpose':'Hydropower (760MW), irrigation, navigation','risk_level':'very_high','downstream_states':'Niger, Kwara, Kogi, Anambra, Delta, Bayelsa, Rivers','data_source':'NIHSA Dam Database / Britannica','notes':"Nigeria's largest dam. Created Kainji Lake (~500 sq miles). In 1999, uncoordinated gate opening flooded ~60 downstream communities. In 2022, dam was near capacity — simultaneous release with Jebba and Shiroro caused catastrophic downstream flooding."},
    {'name':'Jebba Dam','river_basin':'Niger','state':'Niger / Kwara','country':'Nigeria','latitude':9.1167,'longitude':4.8333,'capacity_mcm':3500,'height_m':42,'year_completed':1985,'purpose':'Hydropower (578MW), flood control, navigation','risk_level':'high','downstream_states':'Kwara, Kogi, Niger (confluence), Anambra, Delta, Bayelsa','data_source':'NIHSA / Britannica Niger Dams Project / Wikipedia','notes':'103km downstream from Kainji Dam. Compound effect: when Kainji and Jebba both release simultaneously, communities between and below face double surge.'},
    {'name':'Shiroro Dam','river_basin':'Kaduna','state':'Niger','country':'Nigeria','latitude':9.9833,'longitude':6.8333,'capacity_mcm':7000,'height_m':95,'year_completed':1990,'purpose':'Hydropower (600MW), irrigation, water supply','risk_level':'high','downstream_states':'Niger, Kaduna, Kogi','data_source':'NIHSA / Wikipedia List of dams in Nigeria','notes':'Third of Niger Dams Project. Located on Kaduna River in Niger State. 600MW generation capacity.'},
    {'name':'Dadin Kowa Dam','river_basin':'Gongola','state':'Gombe','country':'Nigeria','latitude':10.4667,'longitude':11.5000,'capacity_mcm':2800,'height_m':33,'year_completed':1988,'purpose':'Hydropower, water supply (Gombe and Yola cities), irrigation','risk_level':'high','downstream_states':'Gombe, Adamawa, Taraba','data_source':'NIHSA Dam Database / Nigerian Queries','notes':'Multipurpose dam on Gongola River. Downstream communities in Adamawa at risk during controlled releases.'},
    {'name':'Kiri Dam','river_basin':'Gongola','state':'Adamawa','country':'Nigeria','latitude':9.7500,'longitude':12.0333,'capacity_mcm':615,'height_m':20,'year_completed':1982,'purpose':'Irrigation, hydropower, water supply for Shell Petroleum','risk_level':'medium','downstream_states':'Adamawa','data_source':'NIHSA Dam Database','notes':'1.2km long zoned embankment dam with internal clay blanket.'},
    {'name':'Kafin Zaki Dam','river_basin':"Jama'are",'state':'Bauchi','country':'Nigeria','latitude':11.2500,'longitude':11.0000,'capacity_mcm':2000,'height_m':45,'year_completed':None,'purpose':'Irrigation (120,000 ha), water supply, flood control','risk_level':'medium','downstream_states':'Bauchi, Jigawa, Yobe','data_source':'NIHSA Dam Database','notes':"Dam on Jama'are River. Second largest in Nigeria when complete. Project has faced significant delays."},
    {'name':'Tiga Dam','river_basin':'Kano / Duku','state':'Kano','country':'Nigeria','latitude':11.4833,'longitude':8.3667,'capacity_mcm':1820,'height_m':35,'year_completed':1974,'purpose':'Irrigation, water supply, flood control','risk_level':'medium','downstream_states':'Kano','data_source':'NIHSA / ResearchGate hydrological studies','notes':'Creates Tiga Lake. Major source for Kano Irrigation Project.'},
    {'name':'Challawa Gorge Dam','river_basin':'Challawa','state':'Kano','country':'Nigeria','latitude':11.8833,'longitude':7.9667,'capacity_mcm':930,'height_m':40,'year_completed':1992,'purpose':'Water supply, irrigation, flood control','risk_level':'medium','downstream_states':'Kano','data_source':'NIHSA Dam Database','notes':'Supplements Tiga Dam for Kano State water supply and irrigation purposes.'},
    {'name':'Goronyo Dam','river_basin':'Sokoto','state':'Sokoto','country':'Nigeria','latitude':13.4167,'longitude':5.6000,'capacity_mcm':960,'height_m':28,'year_completed':1984,'purpose':'Irrigation, water supply, flood control','risk_level':'medium','downstream_states':'Sokoto, Kebbi','data_source':'NIHSA Dam Database','notes':'On Sokoto River. Provides water for Goronyo Irrigation Project.'},
    {'name':'Bakolori Dam','river_basin':'Rima','state':'Zamfara','country':'Nigeria','latitude':12.4833,'longitude':6.5833,'capacity_mcm':450,'height_m':24,'year_completed':1978,'purpose':'Irrigation (irrigation scheme of 23,000 ha)','risk_level':'low','downstream_states':'Zamfara, Sokoto','data_source':'NIHSA Dam Database','notes':'Earth dam. Primarily serves Bakolori Irrigation Project in Zamfara State.'},
    {'name':'Zobe Dam','river_basin':'Katsina / Rima','state':'Katsina','country':'Nigeria','latitude':12.4667,'longitude':7.6833,'capacity_mcm':754,'height_m':30,'year_completed':1988,'purpose':'Water supply, irrigation, flood control','risk_level':'low','downstream_states':'Katsina','data_source':'NIHSA Dam Database','notes':'Earth dam. Supplies Katsina State with water for domestic and irrigation use.'},
    {'name':'Gurara Dam','river_basin':'Gurara','state':'Niger','country':'Nigeria','latitude':9.6667,'longitude':7.0667,'capacity_mcm':930,'height_m':52,'year_completed':2006,'purpose':'Water transfer to Abuja, irrigation, hydropower','risk_level':'medium','downstream_states':'Niger, FCT','data_source':'NIHSA Dam Database','notes':'Supplies water to Abuja (FCT) via transfer scheme.'},
    {'name':'Oyan Dam','river_basin':'Ogun','state':'Ogun','country':'Nigeria','latitude':7.1667,'longitude':3.2667,'capacity_mcm':270,'height_m':38,'year_completed':1983,'purpose':'Water supply (Lagos metropolitan area), irrigation','risk_level':'medium','downstream_states':'Ogun, Lagos','data_source':'NIHSA Dam Database','notes':'Major water supply source for Lagos metropolitan area. Releases compound flooding in Ogun River basin communities downstream.'},
    {'name':'Ikere George Dam (Owena Dam)','river_basin':'Owena','state':'Ondo','country':'Nigeria','latitude':7.5167,'longitude':5.0500,'capacity_mcm':625,'height_m':43,'year_completed':1985,'purpose':'Water supply, irrigation, hydropower','risk_level':'medium','downstream_states':'Ondo','data_source':'NIHSA Dam Database','notes':'Supplies water to Ondo State communities.'},
    {'name':'Asejire Dam','river_basin':'Osun','state':'Oyo','country':'Nigeria','latitude':7.2833,'longitude':4.2167,'capacity_mcm':190,'height_m':22,'year_completed':1971,'purpose':'Water supply for Ibadan city','risk_level':'low','downstream_states':'Oyo','data_source':'NIHSA / Nigerian Queries','notes':'Creates Asejire Lake on Osun River. 30km east of Ibadan. Major water source for Ibadan municipal supply.'},
    {'name':'Eleyele Dam','river_basin':'Ona','state':'Oyo','country':'Nigeria','latitude':7.4167,'longitude':3.8667,'capacity_mcm':36,'height_m':15,'year_completed':1940,'purpose':'Water supply for Ibadan city','risk_level':'low','downstream_states':'Oyo','data_source':'NIHSA / Nigerian Queries','notes':'One of the oldest dams in Nigeria. Supplements Asejire for Ibadan water supply.'},
    {'name':'Obudu Dam','river_basin':'Cross River','state':'Cross River','country':'Nigeria','latitude':6.6667,'longitude':9.1500,'capacity_mcm':4,'height_m':15,'year_completed':1999,'purpose':'Farm irrigation, tourism, fishing, recreation','risk_level':'low','downstream_states':'Cross River','data_source':'Nigerian Search Guide / NIHSA','notes':'Commissioned for farm irrigation and eco-tourism at Obudu Cattle Ranch.'},
    {'name':'Jibiya Dam','river_basin':'Jibiya','state':'Katsina','country':'Nigeria','latitude':13.0833,'longitude':7.2333,'capacity_mcm':160,'height_m':20,'year_completed':1995,'purpose':'Water supply, irrigation, flood control','risk_level':'low','downstream_states':'Katsina','data_source':'NIHSA Dam Database','notes':'Supplies communities along Nigeria-Niger border.'},
    {'name':'Zungeru Dam','river_basin':'Kaduna / Niger','state':'Niger','country':'Nigeria','latitude':9.8000,'longitude':6.1500,'capacity_mcm':2700,'height_m':90,'year_completed':2022,'purpose':'Hydropower (700MW)','risk_level':'high','downstream_states':'Niger, Kogi, Anambra, Delta, Bayelsa','data_source':'Full List of Dams Nigeria 2024','notes':'Chinese government-funded $1.2 billion hydroelectric dam. Second largest reservoir in Nigeria after Kainji.'},
    {'name':'Ekuku Dam','river_basin':'Niger tributary','state':'Kogi','country':'Nigeria','latitude':7.5500,'longitude':6.5500,'capacity_mcm':50,'height_m':None,'year_completed':None,'purpose':'Water supply, irrigation, tourism','risk_level':'low','downstream_states':'Kogi','data_source':'NIHSA / Okene LGA records','notes':'Natural landscape dam in Agassa, Okene LGA. Popular tourist attraction. Nearest dam to central Kogi State.'},
    {'name':'Omi Kampe Dam','river_basin':'Kampe','state':'Kogi','country':'Nigeria','latitude':7.6833,'longitude':6.2000,'capacity_mcm':200,'height_m':None,'year_completed':None,'purpose':'Irrigation, water supply','risk_level':'medium','downstream_states':'Kogi','data_source':'Lower Niger Basin Development Authority','notes':'Key irrigation project under the Lower Niger Basin Development Authority in Yagba West LGA.'},
    {'name':'Lagdo Dam','river_basin':'Benue (Cameroon section)','state':'Adamawa / Taraba (downstream)','country':'Cameroon','latitude':8.4000,'longitude':13.7000,'capacity_mcm':7200,'height_m':46,'year_completed':1982,'purpose':'Hydropower, water supply','risk_level':'very_high','downstream_states':'Adamawa, Taraba, Benue, Kogi, Anambra, Delta, Bayelsa, Rivers, Cross River','data_source':'Wikipedia 2022 Nigeria Floods / NEMA / NIHSA AFO 2022 2023 2024','notes':'THE SINGLE MOST DANGEROUS EXTERNAL FLOOD TRIGGER FOR NIGERIA. Every year, Lagdo releases excess water September-October directly into River Benue, causing catastrophic flooding through 9+ downstream Nigerian states. 2022: 600+ deaths, 1.4 million displaced, 2.5 million affected. The Nigerian buffer dam at Dasin Hausa, Adamawa was NEVER built.'},
]

ACQUISITION_AREAS = [
    {'area_name':'Lekki Free Trade Zone (LFTZ)','authority':'Lagos State Government / LFTZ Enterprise','acquisition_type':'completed','state':'Lagos','lga':'Ibeju-Lekki','min_lat':6.3600,'max_lat':6.4800,'min_lng':3.7500,'max_lng':4.0200,'gazette_reference':'Lagos State Gazette Vol. 38 No. 1, January 2006','data_source':'Lagos State Ministry of Lands / LASURA','notes':"Massive government acquisition covering Ibeju-Lekki corridor. Dangote Refinery (world's largest) sits within this zone. Many private land transactions in this area are fraudulent. Charting Information Certificate ESSENTIAL before any purchase here."},
    {'area_name':'Eko Atlantic City Reclamation Zone','authority':'Lagos State Government / South Energyx Nigeria','acquisition_type':'ongoing','state':'Lagos','lga':'Eti-Osa','min_lat':6.4000,'max_lat':6.4350,'min_lng':3.3700,'max_lng':3.4500,'gazette_reference':'Lagos State Gazette 2008','data_source':'Lagos State Ministry of Physical Planning','notes':'Sea reclamation project on Victoria Island waterfront. Entire zone is committed government/concession land. No individual land purchase possible outside official allocation.'},
    {'area_name':'LSDPC Ikorodu Residential Scheme','authority':'Lagos State Development and Property Corporation (LSDPC)','acquisition_type':'completed','state':'Lagos','lga':'Ikorodu','min_lat':6.5700,'max_lat':6.6200,'min_lng':3.4900,'max_lng':3.5500,'gazette_reference':'Lagos State Official Gazette (LSDPC Scheme)','data_source':'LSDPC Registry / Omonile Lawyer','notes':'LSDPC manages committed government acquisition. Individual private purchases are invalid.'},
    {'area_name':'LSDPC Ilupeju Industrial-Residential Scheme','authority':'Lagos State Development and Property Corporation (LSDPC)','acquisition_type':'completed','state':'Lagos','lga':'Mushin','min_lat':6.5450,'max_lat':6.5750,'min_lng':3.3550,'max_lng':3.3900,'gazette_reference':'LSDPC Gazette','data_source':'LSDPC Registry / Omonile Lawyer research','notes':'Ilupeju is listed by Omonile Lawyer and Ome Construction as government acquisition managed by LSDPC. Industrial layout.'},
    {'area_name':'Ajah-Sangotedo Government Acquisition Corridor','authority':'Lagos State Government','acquisition_type':'completed','state':'Lagos','lga':'Eti-Osa','min_lat':6.4450,'max_lat':6.4800,'min_lng':3.5500,'max_lng':3.6300,'gazette_reference':'Lagos State Ministry of Lands Records','data_source':'Ome Construction / Omonile Lawyer','notes':'Most of already-developed Ajah is under government acquisition. CRITICAL: Always obtain Charting Information Certificate before any purchase.'},
    {'area_name':'Amuwo Odofin LSDPC Housing Estate','authority':'Lagos State Development and Property Corporation (LSDPC)','acquisition_type':'completed','state':'Lagos','lga':'Amuwo-Odofin','min_lat':6.4550,'max_lat':6.5000,'min_lng':3.2700,'max_lng':3.3200,'gazette_reference':'LSDPC Gazette','data_source':'LSDPC Registry / Omonile Lawyer','notes':'Committed LSDPC acquisition. Amuwo listed explicitly by Omonile Lawyer as government acquisition zone.'},
    {'area_name':'FCDA Core Zone — Abuja City Centre','authority':'Federal Capital Development Authority (FCDA)','acquisition_type':'completed','state':'FCT','lga':'Abuja Municipal','min_lat':8.9700,'max_lat':9.1400,'min_lng':7.3600,'max_lng':7.6200,'gazette_reference':'Federal Republic of Nigeria Official Gazette No. 55, Vol. 66, Oct 26, 1979','data_source':'AGIS / FCDA','notes':'ALL land in Abuja FCT is owned by the Federal Government under Decree No. 6 of 1976. Land is only allocated (not sold) by FCDA or Area Councils. Any outright purchase from individuals is legally invalid.'},
    {'area_name':'FCDA Gwagwalada Area Council Expansion','authority':'FCDA / Gwagwalada Area Council','acquisition_type':'completed','state':'FCT','lga':'Gwagwalada','min_lat':8.9000,'max_lat':9.0500,'min_lng':7.0200,'max_lng':7.2000,'gazette_reference':'FCT Area Council Allocation Records','data_source':'AGIS / FCT Area Council records','notes':'Gwagwalada Area Council allocates customary land. Title must be verified with Gwagwalada Area Council and subsequently confirmed at AGIS.'},
    {'area_name':'NNPC / NLNG Gas Corridor — Bonny Island','authority':'Nigerian National Petroleum Corporation (NNPC) / NLNG','acquisition_type':'completed','state':'Rivers','lga':'Bonny','min_lat':4.4000,'max_lat':4.5500,'min_lng':7.1000,'max_lng':7.2500,'gazette_reference':'Federal Government Oil & Gas Act','data_source':'NNPC / Federal Government records','notes':'Bonny Island is substantially controlled by NLNG and NNPC oil & gas infrastructure. Private land acquisition extremely restricted.'},
    {'area_name':'NNPC/Chevron Warri Petroleum Zone','authority':'Federal Government / NNPC / Chevron Nigeria','acquisition_type':'completed','state':'Delta','lga':'Warri South','min_lat':5.4900,'max_lat':5.5700,'min_lng':5.6200,'max_lng':5.7500,'gazette_reference':'Petroleum Act / Federal Government Oil Exploration Licence','data_source':'DPR (Department of Petroleum Resources)','notes':'Warri Refinery and Petrochemical Company zone. Private land acquisition in these zones is legally barred.'},
    {'area_name':'ExxonMobil Qua Iboe Petroleum Zone','authority':'Federal Government / NNPC / ExxonMobil Nigeria','acquisition_type':'completed','state':'Akwa Ibom','lga':'Ibeno','min_lat':4.5000,'max_lat':4.7000,'min_lng':7.8000,'max_lng':8.1000,'gazette_reference':'Petroleum Act / OML Licence','data_source':'Department of Petroleum Resources','notes':"ExxonMobil Qua Iboe Terminal — Nigeria's largest crude oil export terminal. No private land acquisition possible."},
    {'area_name':'Aba Free Trade Zone','authority':'Nigerian Export Processing Zones Authority (NEPZA)','acquisition_type':'completed','state':'Abia','lga':'Aba North','min_lat':5.0800,'max_lat':5.1500,'min_lng':7.3200,'max_lng':7.4000,'gazette_reference':'NEPZA Act / Federal Government Gazette','data_source':'NEPZA / Federal Ministry of Industry','notes':'Federal export processing zone under NEPZA administration. No individual land purchase.'},
    {'area_name':'Kano State Government House / GRA Reservation','authority':'Kano State Government','acquisition_type':'completed','state':'Kano','lga':'Kano Municipal','min_lat':11.9900,'max_lat':12.0400,'min_lng':8.5100,'max_lng':8.5600,'gazette_reference':'Kano State Official Gazette','data_source':'Kano State Ministry of Lands','notes':'Government Residential Area (GRA). No private land purchase — allocation only through Kano State Ministry of Lands.'},
]


class Command(BaseCommand):
    help = 'Seed comprehensive Nigerian land risk data (50+ flood zones, 22 dams, 13 acquisition areas)'

    def add_arguments(self, parser):
        parser.add_argument('--dry-run', action='store_true', help='Preview counts without writing')

    def handle(self, *args, **options):
        dry = options.get('dry_run', False)
        self.stdout.write('\n══════════════════════════════════════════')
        self.stdout.write('  Landrify — Seeding Nigerian Land Risk Data')
        self.stdout.write('══════════════════════════════════════════\n')
        if dry:
            self.stdout.write(self.style.WARNING('DRY RUN — no data will be written\n'))

        if not dry:
            for d in FLOOD_ZONES:
                lookup = {
                    'zone_name': d['zone_name'],
                    'state': d['state'],
                    'lga': d.get('lga', ''),
                }
                defaults = {k: v for k, v in d.items() if k not in lookup}
                FloodRiskZone.objects.update_or_create(**lookup, defaults=defaults)
        self.stdout.write(self.style.SUCCESS(f'{"[DRY RUN]" if dry else "✓"} {len(FLOOD_ZONES)} flood risk zones'))

        if not dry:
            for d in DAMS:
                lookup = {
                    'name': d['name'],
                    'state': d.get('state', ''),
                }
                defaults = {k: v for k, v in d.items() if k not in lookup}
                Dam.objects.update_or_create(**lookup, defaults=defaults)
        self.stdout.write(self.style.SUCCESS(f'{"[DRY RUN]" if dry else "✓"} {len(DAMS)} dams'))

        if not dry:
            for d in ACQUISITION_AREAS:
                lookup = {
                    'area_name': d['area_name'],
                    'state': d['state'],
                    'lga': d.get('lga', ''),
                }
                defaults = {k: v for k, v in d.items() if k not in lookup}
                AcquisitionArea.objects.update_or_create(**lookup, defaults=defaults)
        self.stdout.write(self.style.SUCCESS(f'{"[DRY RUN]" if dry else "✓"} {len(ACQUISITION_AREAS)} acquisition areas'))

        self.stdout.write(self.style.SUCCESS(
            f'\n{"✅ Seed complete" if not dry else "[DRY RUN] Preview"} — '
            f'{len(FLOOD_ZONES)} zones | {len(DAMS)} dams | {len(ACQUISITION_AREAS)} areas\n'
        ))
