# Generated by Django 5.0.6 on 2026-03-22 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('agent', 'Real Estate Agent'), ('developer', 'Developer'), ('bank', 'Bank / Financial Institution')], default='individual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('basic', 'Basic (Free)'), ('pro', 'Pro (Paid)')], default='basic', max_length=10)),
                ('pro_activated_at', models.DateTimeField(blank=True, null=True)),
                ('pro_expires_at', models.DateTimeField(blank=True, null=True)),
                ('interswitch_customer', models.CharField(blank=True, max_length=100)),
                ('basic_scan_used', models.BooleanField(default=False)),
                ('nin_verified', models.BooleanField(default=False)),
                ('nin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('nin_last_four', models.CharField(blank=True, max_length=4)),
                ('nin_full_name_matched', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
