# Generated by Django 5.0.6 on 2026-03-22 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('river_basin', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('capacity_mcm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_level', models.CharField(default='medium', max_length=20)),
                ('data_source', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'dams',
            },
        ),
        migrations.CreateModel(
            name='LandScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_reference', models.CharField(max_length=30, unique=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('radius_km', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('address', models.TextField(blank=True)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('scan_type', models.CharField(choices=[('basic', 'Basic (Free — 1 scan, summary report'), ('pro', 'Pro (Paid — unlimited, AI report)')], default='basic', max_length=20)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_government_land', models.BooleanField(null=True)),
                ('is_under_acquisition', models.BooleanField(null=True)),
                ('acquisition_authority', models.CharField(blank=True, max_length=255)),
                ('acquisition_type', models.CharField(blank=True, max_length=50)),
                ('gazette_reference', models.CharField(blank=True, max_length=255)),
                ('legal_notes', models.TextField(blank=True)),
                ('flood_risk_level', models.CharField(blank=True, max_length=20)),
                ('flood_zone_name', models.CharField(blank=True, max_length=255)),
                ('flood_data_source', models.CharField(blank=True, max_length=100)),
                ('erosion_risk_level', models.CharField(blank=True, max_length=20)),
                ('nearest_dam_name', models.CharField(blank=True, max_length=255)),
                ('nearest_dam_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dam_risk_level', models.CharField(blank=True, max_length=20)),
                ('elevation_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ai_report', models.TextField(blank=True)),
                ('ai_report_model', models.CharField(blank=True, max_length=100)),
                ('ai_report_tokens', models.IntegerField(blank=True, null=True)),
                ('report_generated', models.BooleanField(default=False)),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_required', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'land_scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedLand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_lands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=255)),
                ('authority', models.CharField(max_length=255)),
                ('acquisition_type', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('min_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('max_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('min_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('max_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('gazette_reference', models.CharField(blank=True, max_length=255)),
                ('date_gazetted', models.DateField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'acquisition_areas',
                'indexes': [models.Index(fields=['state', 'lga'], name='acquisition_state_c071bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='FloodRiskZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('min_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('max_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('min_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('max_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flood_risk_zones',
                'indexes': [models.Index(fields=['state', 'lga'], name='flood_risk__state_3be65f_idx'), models.Index(fields=['risk_level'], name='flood_risk__risk_le_118151_idx')],
            },
        ),
    ]
