# Generated by Django 5.0.6 on 2026-03-22 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landscan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedland',
            name='land_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='scans.landscan'),
        ),
        migrations.AddField(
            model_name='savedland',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='landscan',
            index=models.Index(fields=['user', '-created_at'], name='land_scans_user_id_dce4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='landscan',
            index=models.Index(fields=['scan_reference'], name='land_scans_scan_re_5bd5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='landscan',
            index=models.Index(fields=['state', 'lga'], name='land_scans_state_4b5a74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedland',
            unique_together={('user', 'land_scan')},
        ),
    ]
