<<<<<<< codex/integrate-django-backend-with-react-frontend-pxu3u7
# Generated by Django 5.1.15 on 2026-03-27 20:23
=======
# Generated by Django 5.1.15 on 2026-03-27 21:29
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< codex/integrate-django-backend-with-react-frontend-pxu3u7
        ("scans", "0002_initial"),
=======
        ('scans', '0002_initial'),
>>>>>>> main
    ]

    operations = [
        migrations.AddField(
<<<<<<< codex/integrate-django-backend-with-react-frontend-pxu3u7
            model_name="acquisitionarea",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dam",
            name="country",
            field=models.CharField(blank=True, default="Nigeria", max_length=50),
        ),
        migrations.AddField(
            model_name="dam",
            name="downstream_states",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dam",
            name="height_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="dam",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dam",
            name="purpose",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dam",
            name="year_completed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="floodriskzone",
            name="flood_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="floodriskzone",
            name="last_major_flood_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="floodriskzone",
            name="peak_months",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="landscan",
            name="dam_capacity_mcm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="landscan",
            name="dam_downstream_states",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="landscan",
            name="dam_height_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="landscan",
            name="dam_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="landscan",
            name="dam_purpose",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="landscan",
            name="dam_river_basin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="landscan",
            name="dam_year_completed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landscan",
            name="flood_last_major_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landscan",
            name="flood_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="landscan",
            name="flood_peak_months",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="landscan",
            name="flood_type",
=======
            model_name='acquisitionarea',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dam',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=50),
        ),
        migrations.AddField(
            model_name='dam',
            name='downstream_states',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dam',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dam',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dam',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dam',
            name='year_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodriskzone',
            name='flood_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floodriskzone',
            name='last_major_flood_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodriskzone',
            name='peak_months',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='dam_capacity_mcm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='dam_downstream_states',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landscan',
            name='dam_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='dam_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='dam_purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landscan',
            name='dam_river_basin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landscan',
            name='dam_year_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='flood_last_major_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='flood_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='flood_peak_months',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landscan',
            name='flood_type',
>>>>>>> main
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
