# Generated by Django 5.1.15 on 2026-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodriskzone',
            name='flood_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floodriskzone',
            name='last_major_flood_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodriskzone',
            name='peak_months',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
