# Generated by Django 5.1.15 on 2026-03-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_acquisitionarea_notes_dam_country_and_more'),
        ('scans', '0003_floodriskzone_flood_type_and_more'),
    ]

    operations = [
    ]
