# Generated by Django 5.1.15 on 2026-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_acquisitionarea_notes_dam_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscan',
            name='weather_current',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='weather_historical',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='weather_projection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='weather_summary',
            field=models.TextField(blank=True),
        ),
    ]
