# Generated by Django 5.1.15 on 2026-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_landscan_weather_current_landscan_weather_historical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscan',
            name='address_hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landscan',
            name='satellite_image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='landscan',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='landscan',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='landscan',
            name='radius_km',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
    ]
